### ISSUE TITLE
Buttons disappearing on large ship

### ISSUE THREAD

**Issue by ThatPolishKid99** [darkevilmac/archimedes-ships-plus#1]
I have a 6000+ block ship that i use in my Cauldron Server...Whenever i mount the ship, then dismount, a random assortment of buttons on my ship disappear, and these buttons are very important, as they are used for Cannons, in the Cannon plugin

**Comment by darkevilmac** [comment]
I'm assuming if you were to activate the ship, then disassemble without moving the buttons will stay? If so, this is an issue with ship rotation, the main issue with this is that it would have to be stored what side of a block it was placed on initially then move them based on that.

**Comment by notchriss** [comment]
I have the same issue, but buttons disappear even if ship is always parked facing the same original direction

**Comment by darkevilmac** [comment]
Unable to replicate on Alpha-0 please try that version and see if the issue persists.

**Comment by notchriss** [comment]
I recently started a new world and made a new ship, issue seems to be gone now. I didn't update Archimedes Ships though, so probably the bug occurs under some specific rare conditions only.

**Comment by darkevilmac** [comment]
I'm unable to replicate the issue at all.
