### ISSUE TITLE
Crash Server Sponge 1.10.2

### ISSUE THREAD

**Issue by Raghounet** [darkevilmac/archimedes-ships-plus#100]
Hello,

I try to install Movingworld (and Davincis Vessels) on a Sponge Server 1.10.2 and the server chash on launch.

Server version : 	sponge-forge-1.10.2-2123-6.0.0-BETA-1876.jar

**Comment by darkevilmac** [comment]
Please put the crash log on pastebin as well as the full latest-log file, this is just hard to read.

**Comment by Raghounet** [comment]
latest-log :
http://pastebin.com/T4G7hMA3

fml-server-latest_log
http://pastebin.com/2v8s8cJ8

**Comment by darkevilmac** [comment]
I'm just going to keep this open for future reference. If you rename your sponge jar to _sponge-version.jar the game will launch. It's not something I can make a work around for myself.

So, just prefix the sponge jar name with an underscore. It needs to load before movingworld.

**Comment by Raghounet** [comment]
Thank you very much. The server start correctly. I will try to connect to the server tonight.

**Comment by Raghounet** [comment]
Hello,
All Work Perfectly like this.

Thanks a lot.

**Comment by exaskye** [comment]
I'm reopening this issue so it's easy to find if others have this issue, as Darkevilmac wanted.

**Comment by darkevilmac** [comment]
Closing, shouldn't be happening anymore.
