### ISSUE TITLE
Functional blocks?

### ISSUE THREAD

**Issue by QuibblingAsh42** [darkevilmac/archimedes-ships-plus#101]
Apologize for posting this here, but comments appear to be disabled on the Curse Forge pages.  

On the FAQ, you mention adding support for functional blocks, could you expand on that?  What I'm thinking is if, for example, I add a crafting table to my ship build that I'd be able to click on it and use it normally.  In other words, right-clicking the single block would bring up the crafting interface, but if I clicked on any other I'd mount my ride.  

Is that a correct understanding?  If so, that would be magnificent!  Especially if I can do that with things like chests, etc.

**Comment by darkevilmac** [comment]
I've disabled those comments so people will stick to the forums, the adding functionality part is for mod developers. It allows them to still update their tiles while they're on a ship.
