### ISSUE TITLE
[ClientSide] [Bug] Helms render is broken in new 1.10.2 release

### ISSUE THREAD

**Issue by spraaq** [darkevilmac/archimedes-ships-plus#103]
I remember this mentioned before in the forums, the helm "sway" as you change directions.

**Comment by darkevilmac** [comment]
Pictures please.

**Comment by ghost** [comment]
Here's an example; http://i.imgur.com/CiIrV2W.png
And another; http://i.imgur.com/3eP5YGp.png (the wheel of the helm is just visible under the craft)

The wheel will move around the circumference of a circle that appears to be centered on the left or right edge of the craft. Which edge it rotates around seems to be determined by which way the Ship's Helm is facing when the craft is assembled.

**Comment by darkevilmac** [comment]
> Here's an example; http://i.imgur.com/CiIrV2W.png
> And another; http://i.imgur.com/3eP5YGp.png (the wheel of the helm is just visible under the craft)
> 
> The wheel will move around the circumference of a circle that appears to be centered on the left or right edge of the craft. Which edge it rotates around seems to be determined by which way the Ship's Helm is facing when the craft is assembled.

Is the helm rotating properly on disassemble, just trying to rule out something that I've tried on my end.

**Comment by ghost** [comment]
Sorry, I realise my description was lacking an important detail; the helm's wheel moves incorrectly (as demonstrated in the pictures) when you turn the craft left or right. Block orientation is correct upon disassemble, if that's what you're asking.

**Comment by darkevilmac** [comment]
> Sorry, I realise my description was lacking an important detail; the helm's wheel moves incorrectly (as demonstrated in the pictures) when you turn the craft left or right. Block orientation is correct upon disassemble, if that's what you're asking.

Definitely not an issue with your description, I was checking for something sort of unrelated. Anyways, looks like I've gotten things fixed on my end. 

Here's a Video: https://gfycat.com/ImmaculateJoyfulGermanspaniel
