### ISSUE TITLE
Crash on Assembly

### ISSUE THREAD

**Issue by Achilles9802** [darkevilmac/archimedes-ships-plus#106]
Experiencing consistent crashing while trying to assemble anything over a few hundred blocks (have tried slowly adding blocks and assembling successfully up until 400~ blocks), using only vanilla blocks (Oak planks, fences, ladders, torches). I have tried both versions of DavincisVessels and MovingWorld along with forge versions 12.18.2.2099 and 12.18.2.2125 all resulting in the exact same error on both server and client in singleplayer.

http://pastebin.com/pQdxYYHZ

**Comment by darkevilmac** [comment]
Can you create the same structure and send the world file please? I've just created a ship 800 blocks in size without this issue. Alternatively I need width length and height of the structure.

**Comment by Achilles9802** [comment]
The uncompleted boat in this world results in the crash for me.

[New World.zip](https://github.com/elytra/DavincisVessels/files/596193/New.World.zip)

**Comment by darkevilmac** [comment]
Well this was caused by some underlying me being stupid.
