### ISSUE TITLE
Ship does not auto-disassemble upon disembark? 

### ISSUE THREAD

**Issue by Diamond-Taco** [darkevilmac/archimedes-ships-plus#107]
Hi Darkevilmac, 

I've recently gotten back to playing Minecraft, and I realized that now Davincis Vessels is the continuation of the old Archimedes Ship mod. However, when I built an air ship today and assembled my ship together at the helm, I noticed that the ship no longer disassembles into its individual blocks after I disembark the ship. This feature used to be in Archimedes ship mod, and I found it very useful since I could end up building a giant moveable base. However at the moment due to the fact that the ship still remains as a whole after I disembark, I'm not able to access the chest I've placed inside the ship. All that happens when I right click anywhere on the ship is that I get teleported inside again as the driver. The ship also remains together with a large cube collision box around it, suggesting that it has not disassembled itself upon disembark as I anticipated before. I've searched around this website and in Google for almost 30 mins but did not find anything that sounded like this. Is it something really obvious that I missed, or is there specific way to disassemble the ship back to its blocks now? Will the items I've placed inside the chest on my ship disappear if I disassemble the ship somehow? 

If this is not the case then is it possible for you to add this feature back to the mod in the future, as I find it very useful. 

Thanks,  

PS: Sorry if I posted this in the wrong section, but I'm not that familiar with using github. Apologies if I started this thread at the wrong location.

**Comment by darkevilmac** [comment]
Read your controls settings, disassemble with a button. Also the config has
an option to disassemble on dismount.
