### ISSUE TITLE
1.10.2 Crash on startup alongside with WTF's Expedition mod

### ISSUE THREAD

**Issue by spraaq** [darkevilmac/archimedes-ships-plus#108]
Forge:  1.10.2-forge1.10.2-12.18.1.2094 (latest version crashes too)

DV/MW version: Latest 0003

WTF's Expedition: WTF-Expedition_1.10.2_v1.1
( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2703761-wtfs-expedition-cavebiomes-ores-trees-and-more )

Crash report:
http://pastebin.com/gDMXr47s

My uneducated guess would be that either the ore replacment feature or the stalagmites are the culprits.

**Comment by darkevilmac** [comment]
@WhiskyTangoFox From what I see on your repo this exception should be caught.

Nothing I can do from my end to my knowledge.
