### ISSUE TITLE
1.10.2 Server crash (not startup)

### ISSUE THREAD

**Issue by Xasder** [darkevilmac/archimedes-ships-plus#109]
Hi! After 2 days of perfect work had 2 crashes today. Logs included.

[crash-2016-11-18_20.16.57-server.txt](https://github.com/elytra/DavincisVessels/files/601016/crash-2016-11-18_20.16.57-server.txt)
[crash-2016-11-18_20.57.11-server.txt](https://github.com/elytra/DavincisVessels/files/601015/crash-2016-11-18_20.57.11-server.txt)

**Comment by darkevilmac** [comment]
Duplicate of #105
