### ISSUE TITLE
Internal Server error when placing Anchor Point

### ISSUE THREAD

**Issue by kimfy** [darkevilmac/archimedes-ships-plus#11]
I'm getting an internal server error when placing the Anchor Point in MP, I'm on version [1.7.10-10.13.0.1198]ArchimedesShipsPlus-universal-1.7.10.B-Plus. It kicks me off when I place it. Here's a log: http://pastebin.com/CFe9ieuU.

**Comment by Alaberti** [comment]
Are you running a bukkit server? Try running a Forge server on your computer and see if that replicates the issue.

**Comment by darkevilmac** [comment]
Please label issues correctly, I will look into this it seems to be an issue with writeToNBT
