### ISSUE TITLE
Mobs/Entities disrupting ships

### ISSUE THREAD

**Issue by CalebR-300** [darkevilmac/archimedes-ships-plus#112]
Issue: Mobs or Entities (i.e. boats) in the path of the ship (regardless if they hit you or vice versa) can end up lodged in the ship, resulting in the ship being very hard to move/rotate, often immobilizing it altogether.

Suggested solution: Kill mobs and break certain entities on collision with the ship. Maybe make it a config option.

**Comment by darkevilmac** [comment]
Unable to reproduce, you just clip directly through the mobs on my end. Does this occur with vanilla mobs or modded mobs?

**Comment by CalebR-300** [comment]
Apologies for not checking my emails in a week. It happens with vanilla mobs, particularly squids (especially when they swim up under the ship).

It's possible I was colliding with something else whilst hitting the mobs - the bounding box of my ship seems to be 3 blocks wider than the ship itself (which I confirmed when trying to dock directly against a custom built platform).

Anyway, if you can't replicate the problem, it might just be my end.


Thanks for checking it out, and sorry again for the late reply.


Cheers,

Caleb

________________________________
