### ISSUE TITLE
Disappearing Ships after restart

### ISSUE THREAD

**Issue by Amcio** [darkevilmac/archimedes-ships-plus#120]
I'm running a server, after a restart all ships vanished! They were disassembled. This also happens in singleplayer. Only DV and MovingWorld are installed.
Versions(DV and MovingWorld): 0006-full 
Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185

**Comment by darkevilmac** [comment]
There's no reason this would happen at all, ships once disassembled are just blocks. I can't reproduce this on my end whatsoever.
