### ISSUE TITLE
Ship not detecting multiple passenger's seats

### ISSUE THREAD

**Issue by sblectric** [darkevilmac/archimedes-ships-plus#121]
If one passenger is already mounted to a ship, another player cannot sit even if there are free seats.

Forge version: 1.10.2-12.18.3.2185
DV version: 1.10.2-0006
MW version: 1.10.2-0006

**Comment by proEndreeper** [comment]
I'm having the same issue.

Forge version: 1.10.2-12.18.3.2281
DV version: 1.10.2-0006
MW version: 1.10.2-0007

**Comment by darkevilmac** [comment]
Fixed on 1.12.
