### ISSUE TITLE
[Suggestion] Improved submarine detection.. ballast tanks

### ISSUE THREAD

**Issue by winsrp** [darkevilmac/archimedes-ships-plus#122]
Hi, 

I was trying to make a sub, and after making my nice little sub I noticed it didn't work, so I went and looked at the video, and the way you are calculating it, well, it really doesn't allows you to free form your sub. Since this is minecraft and things really don't have to look real to work well, I was thinking why don't you add colored "ballast tanks" blocks in the same way balloon blocks work, just ask for a "ballast tank" ratio in your build and if it has it it will sink, and if it doesn't it will not, plain and simple.

thanks.

-Winsrp

**Comment by winsrp** [comment]
Added to this, you could also add air blocks, so the player fills the walk-able space with air blocks so you know what parts to fill with air when the ship stops, and what to keep with water.

You could also make this blocks totally transparent and only visible with some sort of tool in your hand, like a maze or something. So they don't get in the way of the player, there are tons of ways to do that kind of thing. =D

**Comment by darkevilmac** [comment]
I was considering making it just a minimal not fillable block count like 24 or something...

**Comment by darkevilmac** [comment]
Closed, the mod is essentially in a feature freeze for the time being. Focused on maintenance.
