### ISSUE TITLE
Dismount weirdness.

### ISSUE THREAD

**Issue by 63502** [darkevilmac/archimedes-ships-plus#123]
When I dissasemble a ship/airship/submersible, the ship dismounts me somewhere randomly far out in front of or far above the vessel instead of standing behind the wheel. This is especially apparent with very tall or long vessels that I build.

davincisvessels-1.10.2-0006-full.jar
movingworld-1.10.2-0006-full.jar

Forge 1.10.2 - 12.18.3.2185

**Comment by Twonz** [comment]
same problem. getting launched like 5 blocks forward when dismounting.

davincisvessels-1.10.2-0006-full.jar
movingworld-1.10.2-0006-full.jar
Forge 1.10.2 - 12.18.3.2221

**Comment by Victorietti** [comment]
Same for me, I've done some ''Experiments'' - green block is where i was sitting and red is when i landed after dismounting. Longer vessel - farther place of landing...  and it's same in all directions. It only happens to me in survival and adventure game mode.
![2017-02-20_00 40 19](https://cloud.githubusercontent.com/assets/25888307/23130994/b1571d58-f788-11e6-8eec-608a5abb5f5c.png)

**Comment by darkevilmac** [comment]
Most likely a miscalculation based on the width of the vessel. I've been
focusing more on MovingWorld-Redux lately but I'll take a look when I get a
chance.

**Comment by Alaberti** [comment]
Has there been any progress on correcting this issue?

**Comment by darkevilmac** [comment]
Fixed on 1.12.
