### ISSUE TITLE
Error log at Server startup. No block found.

### ISSUE THREAD

**Issue by ErikSteiner** [darkevilmac/archimedes-ships-plus#126]
Minecraft 1.7.10
Forge: 1.7.10 - 10.13.4.1614
Mod: Archimedes Ships Plus 1.7.10 1.8.1

This error is as old as I can remember doing things with my Server, but I forgot how I am able to fix it, or even if it is a critical issue. I haven't tweaked the Main.cfg, so this is the file that was created after the Server started.
[Main.cfg](http://pastebin.com/njzgSQ8F)

This is the error log:
```
[Server thread/WARN] [MovingWorld/MovingWorld]: No block found for ArchimedesShips:floater at block_densities[0]
[Server thread/WARN] [MovingWorld/MovingWorld]: No block found for ArchimedesShipsPlus:balloon at block_densities[1]
```

This is the whole log file of the server: [LINK ](http://pastebin.com/FVTj4SQX)

**Comment by xXJamieXx** [comment]
Those lines are clearly just warning, "WARN", so unless i'm wrong, that would not be the cause of a crash.
If you were to send the log file again (because it say s it was removed), then someone might be able to figure out whats crashing your server,

**Comment by darkevilmac** [comment]
> Those lines are clearly just warning, "WARN", so unless i'm wrong, that would not be the cause of a crash.
> If you were to send the log file again (because it say s it was removed), then someone might be able to figure out whats crashing your server,

Correct, this is not a fatal error.
