### ISSUE TITLE
Update MovingWorld's Mixin version to 0.6.6-SNAPSHOT

### ISSUE THREAD

**Issue by Aaron1011** [darkevilmac/archimedes-ships-plus#129]
[An issue with Mixin](https://github.com/SpongePowered/Mixin/issues/153) that prevented MovingWorld and SpongeForge from loading together was recently fixed. However, since MovingWorld comes before Sponge alphabetically, the version of Mixin provided by MovingWorld ends up being used.

It would be very helpful if you could bump the Mixin version of MovingWorld for 1.10 and 1.11, so that it's able to function properly alongside SpongeForge.

**Comment by darkevilmac** [comment]
Rename sponge jar to _sponge, unless something has changed since my last experience with this issue that's the current solution.

**Comment by simon816** [comment]
The problem can be solved altogether with no extra steps for the user with the latest version of Mixin.

**Comment by darkevilmac** [comment]
@simon816 
> The problem can be solved altogether with no extra steps for the user with the latest version of Mixin.

Ah, I'll make a new movingworld build in the next little bit.

**Comment by darkevilmac** [comment]
I haven't tested this at all but it's now up on curse: https://minecraft.curseforge.com/projects/movingworld/files/2372902

If something is messed up let me know and I'll just reopen this issue.
