### ISSUE TITLE
Extended gauges revert to normal after disassembly

### ISSUE THREAD

**Issue by ajrb** [darkevilmac/archimedes-ships-plus#13]
If you use an extended gauge on your airship it works fine after the first assemble, but when disassembling the gauge reverts to the normal one. Guessing it's not storing the dmg value or something. This basically makes the extended gauge useless.

**Comment by darkevilmac** [comment]
Please tag issues correctly.

**Comment by darkevilmac** [comment]
Beginning work on this now.

**Comment by darkevilmac** [comment]
Unable to replicate, closed until further notice.

**Comment by darkevilmac** [comment]
Was able to replicate, you need to rotate the ship for it to happen. This is most likely an issue with MetaRot
