### ISSUE TITLE
Broken Bed Recipe

### ISSUE THREAD

**Issue by nyanlathotep** [darkevilmac/archimedes-ships-plus#130]
#### Issue:
The recipe for the secured bed appears to be registered with the block, which has no item version, rather than the item. This has an unfortunate interaction with CraftTweaker, which causes it to fail dumping recipes halfway through when encountering the recipe with a null output.

#### Versions:
AS: 1.10.2-0006
MovingWorld: 1.10.2-0007
Forge: 12.18.3.2.2185
Minecraft: 10.2

#### Logs:
These relate more to CraftTweaker, but here are the logs:
[latest.log](https://gist.github.com/nyanlathotep/63f74b68d92e36dc5f77b553f50f7ad2#file-latest-log)
[direct link to the exception](https://gist.github.com/nyanlathotep/544311fb695a021a59f9385d54b2f010#file-latest-log-L367)
[minetweaker.log](https://gist.github.com/nyanlathotep/63f74b68d92e36dc5f77b553f50f7ad2#file-minetweaker-log)

**Comment by darkevilmac** [comment]
That's a CraftTweaker bug.

**Comment by PlantBlockland** [comment]
I feel bad for asking this, but what is the recipe for the secured bed? I can't find it anywhere on the internet, at ALL.

**Comment by LemmaEOF** [comment]
It's a bed and an iron ingot, shapeless. [Here's](https://github.com/elytra/DavincisVessels/blob/1.12/src/main/java/com/elytradev/davincisvessels/common/object/DavincisVesselsObjects.java#L163) the part of the code where all the recipes are, if you wanna look at them.

**Comment by PlantBlockland** [comment]
I tried crafting that, but it doesn't work. Apparently it was not implemented.

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2867676-what-is-the-crafting-recipe-for-the-secured-bed-in#c4

**Comment by darkevilmac** [comment]
It's fully implemented, not sure why the recipe wouldn't be working.

**Comment by LemmaEOF** [comment]
@PlantBlockland, what version of the mod/Minecraft are you on? That might have something to do with it.

**Comment by PlantBlockland** [comment]
I am on version 1.12 of Minecraft, and version 1.12-5.335-full of the mod.

**Comment by LemmaEOF** [comment]
Hm. I think one big thing is that the recipes are still made in Java, instead of JSON. For future-proofing (since apparently mojang is planning to move to all-JSON recipes in the near future) and just for better ease of use, I think I might go and rewrite all the recipes in the mod in JSON when I have the time.

**Comment by darkevilmac** [comment]
That wouldn't be the cause, the recipe registry still exists and other
recipes are working fine. I'll check and confirm the bug once I'm at my PC.
