### ISSUE TITLE
Can't launche game with the mod

### ISSUE THREAD

**Issue by MojoTM** [darkevilmac/archimedes-ships-plus#131]
Crash message: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Davinci's Vessels (davincisvessels)

**Comment by exaskye** [comment]
Please follow the [contribution guidelines](https://github.com/elytra/DavincisVessels/blob/1.11/CONTRIBUTING.MD). This issue report is completely useless.
