### ISSUE TITLE
Can't launch game with mod

### ISSUE THREAD

**Issue by MojoTM** [darkevilmac/archimedes-ships-plus#132]
Crash log: https://hastebin.com/isunagojiv.sql

**Comment by exaskye** [comment]
:+1:

You're trying to use a 1.10.2 version of DV on 1.11.2.

**Comment by MojoTM** [comment]
Is there a 1.11.2 version of DV, i can't seem to find it?

**Comment by exaskye** [comment]
I don't believe it's finished yet, @Darkevilmac has been working on some pretty major changes to MovingWorld.
