### ISSUE TITLE
Recipes should use oredict

### ISSUE THREAD

**Issue by Landmaster** [darkevilmac/archimedes-ships-plus#133]
Looking at the source code of this mod, it seems that it restricts itself into using vanilla wood and sticks. The recipes should use the oredicts for them instead, to support modded wood and sticks.

**Comment by Landmaster** [comment]
Same goes with the slimeballs, the wood planks, and pretty much every oredict-able item in the mod.

**Comment by darkevilmac** [comment]
Fixed in 1.12.
