### ISSUE TITLE
Ship melted upon mounting

### ISSUE THREAD

**Issue by BBoldt** [darkevilmac/archimedes-ships-plus#134]
Minecraft 1.10.2
Forge 2254
DV 0006
MW 0007

This is your ship:

![](http://i.imgur.com/aKw18Ug.jpg)
![](http://i.imgur.com/EMkAWuI.jpg)

This is your ship on drugs:

![](http://i.imgur.com/1jYWHNn.jpg)

Assemble ship > success > mount ship > RIP

I think it must have either been my copper chests or the malisis doors trap door things that did it.

@DeGariless might have logs somewhere, but idk.

**Comment by adegarimore** [comment]
I have no useful logs. It just shows @BBoldt saying"welp"

**Comment by darkevilmac** [comment]
Well if there's no logs obviously nothing went wrong.

**Comment by darkevilmac** [comment]
I all seriousness though, I'll make a movingworld jar with some extra debug output I can use.

**Comment by darkevilmac** [comment]
Need confirmation on 1.12, closing for now.
