### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by gdarai** [darkevilmac/archimedes-ships-plus#139]
When I start building a ship, I do it as a real ship looks: submerged (partially) in the water. So, let's say ship has 3 floors (hight 3 blocks). So I submerge one and have 2 above water line.

**Observed issues:**
1) When the ship is mounted, there is a hole in the water left... this 'HOLE' drags the ship back and it is wery hard to sail out from this hole.

2) When the ship is unmounted (properly, through ship inventory, with stop, align, dismount) It is never sure, where the ship will be stopped if also with one block submerged or if all above water.... which can look strange... when the ship was originally sbmerged and now is all above water.

3) When the ship is unmounted, the driver is often thrown from the ship into the water.

**Question:** So, how to do it properly? What is the best practice?

**Comment by darkevilmac** [comment]
Build ABOVE the water.
