### ISSUE TITLE
game crashes when mounting ship

### ISSUE THREAD

**Issue by arronski** [darkevilmac/archimedes-ships-plus#142]
my game crashes when mounting the ship. I believe  it is to do with the entity crates as it only seems to happen when they have been placed on the ship. Here is the crash log https://hastebin.com/majaxupoma.pas

**Comment by CalmBit** [comment]
This seems to be an issue related to [MovingWorld](https://github.com/elytra/MovingWorld) rather than DV - you might be asked to post this there instead.

**Comment by CalmBit** [comment]
Possibly impromper, but I moved this issue to [here](https://github.com/elytra/MovingWorld/issues/42).

**Comment by darkevilmac** [comment]
Missing information and the issue was made for 1.11.
