### ISSUE TITLE
[1.8.0] Ships glitches

### ISSUE THREAD

**Issue by Rad200** [darkevilmac/archimedes-ships-plus#144]
Not exactly, also sorry for bothering people with an old version.
It is just whenever I sail and new chunks are loading in the boat just temporarily disappears.
It is quite frustrating to try enjoy a sail through the seas only to get your immersion cut off with a disappearing ship!
Hopefully I won't be a bother and someone could help me.

**Comment by darkevilmac** [comment]
Not possible to fix without some hacking around unfortunately, I didn't notice this on 1.12 though so it may have been fixed on Forge/Mojang's end.
