### ISSUE TITLE
<READ THIS BEFORE REPORTING 1.12 CRASHES> Crashes on outdated Forge without the registry refactor

### ISSUE THREAD

**Issue by Polaris12** [darkevilmac/archimedes-ships-plus#146]
i understand this is a beta and bugs are normal to no hard feelings. ;) its not a problem with moving world, as when i launch it alone it works fine. keep up the great work however, your work is amazing

**Comment by exaskye** [comment]
This bug report is not helpful as is; please include a crash report or log so we can look into this, as well as your DavincisVessel and MovingWorld versions.

**Comment by Polaris12** [comment]
World Mover: movingworld-1.12-2.337-full
Davincis: davincisvessels-1.12-2.331-full

hope i can help you, im sort of new to this bug reporting thing =L

Edit by @unascribed: Convert inline crash report to gist.

https://gist.github.com/unascribed/d139b5f38e14fea95a1e782ebb85feaa

**Comment by exaskye** [comment]
Your Forge version is outdated, please update to the latest.

**Comment by Polaris12** [comment]
thankyou very much

**Comment by Polaris12** [comment]
ahh i found the problem, this mod is not compatible with optifine (at least my version)
Optifine: OptiFine_1.12_HD_U_C2

**Comment by Polaris12** [comment]
i had two problems the forge was out of date and optifine is not compatible

**Comment by exaskye** [comment]
Yeah, the error you posted is outdated Forge. I'm not surprised Davinci's doesn't work with OptiFine.

Closing this issue as it seems to be resolved. Reopen if you have this same issue again.
