### ISSUE TITLE
refuses to work with moving worlds

### ISSUE THREAD

**Issue by hashtagmugger** [darkevilmac/archimedes-ships-plus#147]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Davinci's Vessels (davincisvessels), every time o try to launch forge i get this message, or if i attemtp to use diffeent moving worlds it just says i have duplicates

**Comment by darkevilmac** [comment]
Follow the guidelines for creating your issue and try again.
https://github.com/elytra/DavincisVessels/blob/1.12/CONTRIBUTING.MD
