### ISSUE TITLE
Non-sticky buffers are sticking to ships

### ISSUE THREAD

**Issue by gdarai** [darkevilmac/archimedes-ships-plus#148]
In my last issue (#140) I warned you that the buffer sticks to the ship. Not only the sticking one but also the normal one. You closed that issue... so, is it fixed? Or you skipped the warning, because I was fool and put there also a question?

Sorry for reopening this but since that is a bug I want to be sure you noticed that. Thanks for the good work.

**Comment by darkevilmac** [comment]
I'll take a look.

**Comment by darkevilmac** [comment]
Well this is a hell of a late response isn't it? I've tested on the latest version and cannot reproduce the issue.
