### ISSUE TITLE
Crashes when launching

### ISSUE THREAD

**Issue by CcGamers** [darkevilmac/archimedes-ships-plus#149]
i got the 2 mods and there the same version and 0005 or 0006 thing if that even matters but when ever i start the launcher it crashes and i really love this mod and i want it to work so if any one knows how to fix it the contact me

**Comment by exaskye** [comment]
That's a link to your local computer. We can't use that.

Please post your crash report or log to [Gist](https://gist.github.com).

**Comment by darkevilmac** [comment]
Closing due to a lack of response from the issue creator. If you still have this issue create a new issue and follow the guidelines. https://github.com/elytra/DavincisVessels/blob/1.12/CONTRIBUTING.MD
