### ISSUE TITLE
[Undecided] [Help Wanted] I think it would be a good idea to implement RF for flying tiles.

### ISSUE THREAD

**Issue by darkevilmac** [darkevilmac/archimedes-ships-plus#15]
Thoughts? I won't be able to do this alone so I will need help.

**Comment by melekaiah** [comment]
Well do just wanna use rf as power for moving the ships? 

U could do what power converters does. Use the api for the different sources of power. Eu rf etc. 
And set up a ratio for each.

when the compiler finds the ship has a battery Of some type it reads the batterys rf level and uses that as a fuel source foe the engine. And then update said battery on decompile. 

It would make sense to decompile to recharge. 

energy use could also be based on ship size. While compiling with the config holding a rf per block: option. 

but then im not sure this is what u meant by tiles at all.

**Comment by Alaberti** [comment]
If you implement something like this, one of the first things I see being asked is "can this continue getting power from a tesseract/dimensional transceiver wirelessly in-flight?" It would be an impressive feat of coding, I'm not even sure it's possible. I'm assuming you intend an rf-powered engine, which seems feasible enough. Much like your anchor block, a docking block that passes energy into the ship would be pretty neat.

**Comment by darkevilmac** [comment]
@Alaberti I doubt things like tesseracts would work, my main idea is to simply find a way to call methods for the RF api without referencing a world. But if I did this I think it would be a better idea to simply implement MobileChunks to be a world instead.

**Comment by katzenpapst** [comment]
Couldn't tesseracts actually be easier to implement? In theory, you shouldn't even need any blocks, worlds or whatever, just the frequency ID. Of course, you would need to figure out what function calls the tesseract does to request energy...

Other idea: on assembly just add all the RF values of all batteries in the ship, use that to calculate stuff while in transit, and redistribute the rest to the batteries on disassembly

**Comment by darkevilmac** [comment]
Closing this issue, it makes more sense in the long run to just change MovingWorld MobileChunks to be works. This would allow me to run update methods to tiles without any major issues.
