### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by asiekierka** [darkevilmac/archimedes-ships-plus#151]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUKGTHYBNV JLOYGUTHFVJNBRFCDTBHGVNJERDFVETRGSXCFDVEYHTCXS

**Comment by asiekierka** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUKGTHYBNV JLOYGUTHFVJNBRFCDTBHGVNJERDFVETRGSXCFDVEYHTCXS

**Comment by darkevilmac** [comment]
okay

**Comment by asiekierka** [comment]
For future reference:

![](https://img.asie.pl/gAg5)
