### ISSUE TITLE
NO TEXTURE

### ISSUE THREAD

**Issue by flyingpickle** [darkevilmac/archimedes-ships-plus#152]
When i hold or have in my inventory a air baloon there is no texture (pink and black) help?

**Comment by nightcipher** [comment]
Balloon textures work fine with vanilla resource pack, but upon using a resource pack, the balloon textures change to the pink and black 'texture missing' graphic.

**Comment by flyingpickle** [comment]
I don't have any texture pack and I'm in 1.12

**Comment by darkevilmac** [comment]
https://github.com/elytra/DavincisVessels/blob/1.12/CONTRIBUTING.MD
