### ISSUE TITLE
Constant mod troubles

### ISSUE THREAD

**Issue by KobusSWTF** [darkevilmac/archimedes-ships-plus#153]
Every mod i've downloaded worked fine. But davincis vessels and moving world are really a pain in the ***. I have removed all mods and it says that both mods are duplicated. Then i removed moving world and i can load a world (very slowly). After i place one block of the mod it crashes again with no explenation. I have searched the internet for a cause and solution but can't find any solution. I'm propably using the wrong keywords. is there a way to end this endless stream of mod torture.

(i have reinstalled forge and checked if i had all the correct versions. Still doesn't work)

**Comment by darkevilmac** [comment]
Follow the contribution guidelines instead of ranting please. https://github.com/elytra/DavincisVessels/blob/1.12/CONTRIBUTING.MD
