### ISSUE TITLE
[1.12] Missing Textures

### ISSUE THREAD

**Issue by nightcipher** [darkevilmac/archimedes-ships-plus#154]
Mincraft Version: 1.12
MovingWorld Version: 1.12 - 2.337
DavincisVessels Version: 1.12 - 2.331
Forge Version: 14.21.1.2406

Issue:
After first loading in to a world, the textures of all balloon blocks and the extended gauges are missing.

Steps to reproduce:

1- Launch Minecraft with a Resource Pack applied.
2- Load a world.
3- Textures for all colors of Balloons and the Extended Gauges are missing (pink and black checker pattern), but only in JEI or the inventory. Blocks in the world have correct textures.

All other blocks have functioning textures. Textures will appear on inventory items after removing and re-applying the resource pack. Textures will also appear if the world is exited, then re-loaded.

Running ONLY Davincis Vessels and MovingWorld. Tested on 3 different resource packs.

Screenshots:

Resource Pack on, Missing Textures: 
[https://i.gyazo.com/cc56e9028ae0ff6ab9fec0a3c4f1c241.png](url)

Resource Pack on after reloading, Textures Present: 
[https://i.gyazo.com/31c142fe05098119f154c8d56c4a8683.png](url)

**Comment by darkevilmac** [comment]
Thank you for following the guidelines, it looks like there was a change in Forge since the build I released. I think I've managed to fix things on my end, I'll be making a new release in a little while.

**Comment by darkevilmac** [comment]
Fixed and is now available on Curse.
