### ISSUE TITLE
Passenger Seats Simply Not working.

### ISSUE THREAD

**Issue by Abbadonsin** [darkevilmac/archimedes-ships-plus#155]
I'm running a Lanworld with two other people, and none of us are able to sit in the seats even once the ship is assembled. I read a while back on the mc forums that you were working on seat related bugs, and it got me wondering if this is an unresolved issue?

**Comment by zaylivinglive** [comment]
Also Happening here.

**Comment by winsrp** [comment]
same here, seat not working

**Comment by Vilfang** [comment]
I got the same problem. is this mod still being worked on or is it tossed? awsome mod, but seats need to work.

**Comment by LucidLethargy** [comment]
Same problem here. Bit of a bummer.

**Comment by darkevilmac** [comment]
I'll take a look at this in a minute.

**Comment by darkevilmac** [comment]
Fix published to curse, waiting for approval but that usually only takes a minute or two.

EDIT: Approved https://minecraft.curseforge.com/projects/davincis-vessels/files/2459827

**Comment by winsrp** [comment]
holy F^%& you actually fixed it!

**Comment by LucidLethargy** [comment]
Ah shoot, I'm guessing this is only going to be fixed in the latest version of Minecraft? I totally understand if that's the case, but most mods are only supporting 1.10.2 right now, so a lot of servers like mine are tied to this version just in case you ever feel like updating. Either way, I appreciate the responsiveness to the issue!

**Comment by Vilfang** [comment]
Awsome that you fixed it thank you SO much!. but now im struggeling with pickture frames and paintings falling off? is that something that can be fixed too?

**Comment by darkevilmac** [comment]
No, they're entities and can't be stored on ships.
