### ISSUE TITLE
allow flights=false = you get kicked using a flying ship 1.12

### ISSUE THREAD

**Issue by EnderStar** [darkevilmac/archimedes-ships-plus#158]
So the only way to use a flying ship is turning allow flight to true but that allow cheaters fly without any problem, if allow flight is false cheaters cant fly for too long

**Comment by exaskye** [comment]
Vanilla's cheat prevention is placebo at best, and is a massive pain to work around in a mod. I'd recommend just turning it off.

@darkevilmac, are you interested in being compatible with allow-flight=false? If not, I'd just close this issue.

**Comment by darkevilmac** [comment]
Welcome to modded Minecraft, where nocheat comes to die. Closing when I get
a chance.
