### ISSUE TITLE
option for consume of fuel + leave the empty bucket [Feature request]

### ISSUE THREAD

**Issue by EnderStar** [darkevilmac/archimedes-ships-plus#159]
Hi, it would be a very useful feature to have an option to change the amount of fuel consumed per second in the config file and the empty bucket should stay in the engine when using lava buckets or any bucket with fuel.
Also an option to include other fuels and be able to see how many fuel is remaining in the engines from the ship inventory and when you dismount the ship you should stay in the same position so you dont fall if you do it in mid air
Thanks for the awesome mod, i hope that you can add some of this features!

**Comment by CursedFlames** [comment]
I think a config option for fuel consumption would be useful too, the current rate seems way too high to me.

**Comment by darkevilmac** [comment]
Has been added.
