### ISSUE TITLE
A lot of ship blocks become invisible when mounting - but its flying!

### ISSUE THREAD

**Issue by Knito58** [darkevilmac/archimedes-ships-plus#164]
MC 1.12
Forge 14.21.1.2413
Optifine 1.12_HD_U_C4 (Maybe thats it)
DV 1.12.-4.334
MW 1.12-4.340

After clicking "mount" many parts of the ship become invisible. The air ballons, the steam engine and the Measurement Gauge atm. The helm and the chests which I added stay visible. The Measurement Gauge only shows two needles, one blue and one white, the rest is gone.

But hey - it flies!

**Comment by Knito58** [comment]
Disabled Optifine in the mod folder (renamed it to .txt) and the vessel is back in all its glory. Optifine is to be blamed for vanishing ship parts.

**Comment by darkevilmac** [comment]
As a note, this may be due to the changes made to support VBOs, turn off VBOs in your game settings to use the legacy renderer.

**Comment by Knito58** [comment]
You're right. Re-enabling Optifine and setting VBO to off is fine.
![It works now](https://www.dropbox.com/s/9wvgi5eswrhz0o7/davinci-vbo.gif?dl=1)
