### ISSUE TITLE
Can't Load in Minecraft 1.12

### ISSUE THREAD

**Issue by mcfilmmakers** [darkevilmac/archimedes-ships-plus#168]
Monecraft 1.12
Forge: 1.12 14.21.1.2424
Davinci Vessel 1.12-4.334
MovingWorld 1.12-4.340

I get the following error: 
Forge Mod loader has found a problem with your minecraft installation. 
You have mod sources that are duplicate in your system 
Mod Id: File name 
com.elytradev.movingworld.common.asm.coremod : minecraft.jar

No other mods are installed.

fml-client-latest.log: https://pastebin.com/UKFxvdww

**Comment by XvSkItZvX** [comment]
Same Issue...
Monecraft 1.12
Forge: 2443
Davinci Vessel 1.12-5.335
MovingWorld 1.12-5.341

![moving world](https://user-images.githubusercontent.com/9143369/29543922-41aebf7c-86aa-11e7-854f-ea8078b37433.PNG)


Addition..this seems to be a problem across the last three version of "MovingWorld" as using older versions haven't fixed the error either. At this point I feel it necessary to ask if there are any special instructions I have managed to overlook regarding installation of the mod.

**Comment by darkevilmac** [comment]
This is a conflict with liteloader from my understanding as they both use mixins. Remove either Davincis or LiteLoader for the time being.

**Comment by XvSkItZvX** [comment]
good to know, thank you.

**Comment by darkevilmac** [comment]
Should be fixed with the most recent changes that updates mixins. Closing.
