### ISSUE TITLE
Funky Visual Bug when Mounting Airship

### ISSUE THREAD

**Issue by CreepersGamingz** [darkevilmac/archimedes-ships-plus#169]
Hey so when i added the Davincis Vessels mod to my Custom pack it seems the Ship when Mounted(Not assembled just Mounted) Creates this Funky looking Visual Bug.

Visual Bug: [Imgur Link](https://imgur.com/a/vUNgU)

This is on minecraft 1.12 with forge version 14.21.1.2426
on my own pack with Currently 38 Active mods.

Full Modslist:

Additional Banners
Aroma1997Core
Aroma1997s Dimensional World
Better Foliage
BiblioCraft
Chisel
Clarity
ConnectedTexturesMod
Cosmetic Armor Reworked
Davincis Vessels
Dynamic Surroundings
Gravestone Mod - Graves
Hwyla
Immersive Engineering
Improved Hoes
Inventory Tweaks
JourneyMap
JEI - Just Enough Items
Mantle
MouseTweaks
Moving World
NetherChest
Optifine_1.12_HD_U_C4
PassableLeaves
Platforms
Roots
ShetiPhianCore
Tinkers Construct
UnderpHangables

**Comment by exaskye** [comment]
Does this still happen if you turn off VBOs?

**Comment by darkevilmac** [comment]
As @unascribed said, this is a conflict with optifine making some changes to minecraft's render code. The solution is to either remove optifine or disable VBOs.

**Comment by CreepersGamingz** [comment]
Ah yes VBO's seemed to be the Problem. A bit odd but Hey it works now and thats all that matters thanks Dudes :D

**Comment by exaskye** [comment]
Well, since you have OptiFine, that means your issue is a duplicate of #164.
