### ISSUE TITLE
[1.10.2] [JEI]: Found a broken crafting recipe.

### ISSUE THREAD

**Issue by ErikSteiner** [darkevilmac/archimedes-ships-plus#170]
When I only use Just Enough Items (JEI) and DavincisVessels, JEI will give me the information, that a crafting recipe is broken. I don't know how critical that is.

SNIP:
```
[15:22:10] [Client thread/ERROR] [JEI]: Found a broken crafting recipe.
mezz.jei.util.BrokenCraftingRecipeException: net.minecraft.item.crafting.ShapelessRecipes@40b63796
Outputs:
net.minecraft.item.ItemStack: [[1x (null)]]
Inputs:
net.minecraft.item.ItemStack: [[1x (null)], [1xitem.ingotIron@0 minecraft:iron_ingot]]
Caused by: java.lang.NullPointerException: Null item in itemStack
```

Here is the complete log:
[DavincisVessels.txt](https://github.com/elytra/DavincisVessels/files/1184973/DavincisVessels.txt)

**Comment by darkevilmac** [comment]
I had tested DV with JEI and all the recipes seemed to be functioning properly. I wouldn't be concerned.

**Comment by exaskye** [comment]
This is a correctness issue, not a real user-facing issue. Null/empty stacks should never be in a recipe.

**Comment by ErikSteiner** [comment]
I just wanted to let you know of the issue ;)
