### ISSUE TITLE
Crash with chisel and bits

### ISSUE THREAD

**Issue by vivagabe** [darkevilmac/archimedes-ships-plus#175]
I didn't expect chiseled bits to work on ships but is there a way to disable to blacklist the chiseled bit so doesnt try to become part of a ship?

**Comment by darkevilmac** [comment]
Moving world allows blacklisting of blocks, as well as blacklisting of tile entities. Read the configuration.

**Comment by alphapapa** [comment]
@darkevilmac Is there any chance of chiseled blocks working with this mod someday?  The ships we could create with them would be amazing.
