### ISSUE TITLE
1.06

### ISSUE THREAD

**Issue by MadRatSRP** [darkevilmac/archimedes-ships-plus#176]
Edit by unascribed: placed (incomplete) log spam in details block
<details>
<summary>Incomplete log</summary>
java.lang.Thread.getStackTrace(Unknown Source)
com.saftno.compressions.Blocks.Register(Blocks.java:82)
com.saftno.compressions.Items.Register(Items.java:67)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler_210_Items_Register_Register.invoke(.dynamic)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:733)
net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
net.minecraft.client.main.Main.main(SourceFile:123)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Blocks - Generate: start
Blocks - Generate - getSingleIDs: start
Blocks - Generate - getSingleIDs: end 3
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 6
Blocks - Generate - getRelatedIDs: start
Blocks - Generate - getRelatedIDs: end 0
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 0
Blocks - Generate - Recipes.getRelated: start
Blocks - Generate - Recipes.getRelated: end 0
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 0
Blocks - Generate - getSmeltingRelated: start
Blocks - Generate - getSmeltingRelated: end 0
Blocks - Generate - entries: start
Blocks - Generate - entries: end 6
Blocks - Generate - blocks: 0 0
Blocks - Generate - blocks: tile.stonebrick
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 0 1
Blocks - Generate - blocks: tile.stonebrick
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 1 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 1 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 2 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 2 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 3 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 3 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 4 0
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 4 1
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 5 0
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 5 1
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Items - Recipes finished
Languages - LANG: start
Languages - LANG - content: start
Languages - LANG - content: end
Languages - LANG - existing: start
Languages - LANG - existing: end
Languages - LANG - block: tile.minecraft_cobblestone_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_cobblestone_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_0_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_0_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_1_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_1_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_2_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_dirt_2_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_sand_0_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_sand_0_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_sand_1_1x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - block: tile.minecraft_sand_1_2x
Languages - LANG - block: end
Languages - LANG - loc: start
Languages - LANG - loc: end
Languages - LANG - entries: add
Languages - LANG - entries: end
Languages - LANG - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Languages - LANG - mod: start
Languages - LANG - mod: end
Languages - LANG - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Languages - LANG - tmp: start
Languages - LANG - tmp: end
Models - Blockstates: start
Models - Blockstates - block: tile.minecraft_cobblestone_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_cobblestone_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_0_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_0_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_1_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_1_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_2_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_2_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_0_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_0_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_1_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_1_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
java.lang.Thread.getStackTrace(Unknown Source)
com.saftno.compressions.Blocks.Register(Blocks.java:82)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler_212_Blocks_Register_Register.invoke(.dynamic)
net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:733)
net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
net.minecraft.client.main.Main.main(SourceFile:123)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Blocks - Generate: start
Blocks - Generate - getSingleIDs: start
Blocks - Generate - getSingleIDs: end 3
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 6
Blocks - Generate - getRelatedIDs: start
Blocks - Generate - getRelatedIDs: end 0
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 0
Blocks - Generate - Recipes.getRelated: start
Blocks - Generate - Recipes.getRelated: end 0
Blocks - Generate - Items.getAll: start
Blocks - Generate - Items.getAll: end 0
Blocks - Generate - getSmeltingRelated: start
Blocks - Generate - getSmeltingRelated: end 0
Blocks - Generate - entries: start
Blocks - Generate - entries: end 6
Blocks - Generate - blocks: 0 0
Blocks - Generate - blocks: tile.stonebrick
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 0 1
Blocks - Generate - blocks: tile.stonebrick
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 1 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 1 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 2 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 2 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 3 0
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 3 1
Blocks - Generate - blocks: tile.dirt
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 4 0
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 4 1
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 5 0
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Blocks - Generate - blocks: 5 1
Blocks - Generate - blocks: tile.sand
Blocks - Generate - compr: start
Blocks - Generate - compr: end
Blocks - Generate - blocks.Add: start
Blocks - Generate - blocks.Add: end
Textures - Blocks: start
Textures - Blocks - frame: start
Textures - Blocks - frame: end
Textures - Blocks - side: start
Textures - Blocks - side: end
Textures - Blocks - block: tile.minecraft_cobblestone_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_cobblestone_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_0_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_0_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_1_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_1_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_2_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_2_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_0_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_0_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_1_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_1_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-1.12.1-1.0.6.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
</details>

**Comment by exaskye** [comment]
What

**Comment by cenneunborifisms** [comment]
sorry, that was meant for my project

https://github.com/Sediments/Compressions/issues/1
