### ISSUE TITLE
[1.10]Can't get gradle to setupdecompworkspace

### ISSUE THREAD

**Issue by IronworksProductions** [darkevilmac/archimedes-ships-plus#178]
OS: MacOS Sierra
Version: latest source for 1.10
I am trying to develop DavinciVessels but gradle wont even get past setup decomp workspace and thats after i converted your batch scripts to shell.
After finding how small the log was i ran it in debug and this is what i got
https://hastebin.com/evajalikem.pl

**Comment by darkevilmac** [comment]
1.10 is no longer in active development.
