### ISSUE TITLE
[1.12.1] Crash when assembling

### ISSUE THREAD

**Issue by Knito58** [darkevilmac/archimedes-ships-plus#179]
MC 1.12.1
Forge 14.22.0.2456
Moving World 1.12-5.341
Davincis Vessels 1.12-5.335
Game Mode SSP

https://hastebin.com/iqigexecov

Happens all the time. Assembling does not assemble but "Mount" button is enabled. Mounting then eather crashes or does nothing.

**Comment by darkevilmac** [comment]
Probably an issue with 1.12.1 mappings or something. Will take a look.

**Comment by Knito58** [comment]
Thanks. And oops - my link to the crash log is gone. Here it is again:
https://www.dropbox.com/s/so1ompo490sry45/crash-2017-08-16_13.24.44-server.txt?dl=1

**Comment by darkevilmac** [comment]
> Thanks. And oops - my link to the crash log is gone. Here it is again:
> https://www.dropbox.com/s/so1ompo490sry45/crash-2017-08-16_13.24.44-server.txt?dl=1

It's not gone, I mirrored it to hastebin so I can view it on a browser instead of downloading.

**Comment by darkevilmac** [comment]
Closed because this issue is old and should be fixed after I switched a bunch of ATs to Concrete Accessors/Invokers.
