### ISSUE TITLE
[1.10.2] Movingworld conflict with MalisisDoors and Big Doors

### ISSUE THREAD

**Issue by Morozzs** [darkevilmac/archimedes-ships-plus#180]
movingworld-1.10.2-0007-full
Minecraft 1.10.2
Forge-1.10.2-12.18.3.2185

When I have movingworld installed on my client, the big doors are almost impossible to close/destroy unless you target a specific tiny spot. Also in MalisisDoors when you destroy a hi-tech door it's texture (rendered as a missing texture) will remain in stead of the door. Tested with all 1.10.2 versions of MovingWorld.

**Comment by darkevilmac** [comment]
Closed as 1.10 is no longer supported. Sorry.
