### ISSUE TITLE
Ships disappearing in 1.12

### ISSUE THREAD

**Issue by Mattrock607** [darkevilmac/archimedes-ships-plus#182]
My game crashed randomly due to a bug with another mod, while I had my ship assembled and mounted. When I returned to the game, the ship had vanished. When I attempted to log out and log back in again (an old Archimedes trick), the ship was still missing. I rebuilt that vessel exactly the same way and now that one is gone too after a similar crash. It seems these ships will disappear if you sneeze on them and this is not something I ever encountered in earlier versions of this mod (I used it constantly in the 1.7.10 days when it was still Archimedes).

MC Version = 1.12
Forge Version = 1.12-14.21.1.2443
DaVinci's Vessels Version = 1.12-5.335-full
Moving World Version = 1.12-5.341-full

Crash Report: 
NOTE: This crash was not related to the mod as far as I know. The bug is explained in detail above.

https://gist.github.com/Mattrock607/f7be2d810fffc9c72a90f20ca33c7c49

**Comment by darkevilmac** [comment]
The ship failed to save due to a crash most likely. Not a whole lot I can think of that would get around this. If you can provide me some blocks to put on a ship that I can use to reproduce this then let me know but from what I see here its somewhat out of my control.
