### ISSUE TITLE
Mounting a ship causes blocks to no longer drop

### ISSUE THREAD

**Issue by Nebuzaradan42** [darkevilmac/archimedes-ships-plus#189]
I have run into an interesting problem when attempting to create ships using blocks from other mods.  Most of the blocks have worked fine, but certain blocks cause a strange bug.  When I attempt to mount a ship that has certain blocks on it (including the Solar Collector from ProjectE, and ANY ducting from Thermal Expansion) it says that the assembly was successful but a large portion of the ship simply disappears, and you are left not piloting anything.  Even worse once you have done this even once, block drops no longer work (mining dirt, stone, ANYTHING no longer works, the block is destroyed but nothign drops - Yes this is in survival mode).  Closing and reopening the game does not fix this.

Minecraft Ver: 1.12
Forge Ver: 14.21.1.2420
Moving World Ver: 6.342
Davinci's Vessels Ver: 6.337

**Comment by darkevilmac** [comment]
Set doblockdrops back to true with the gamerule command

**Comment by Nebuzaradan42** [comment]
Thanks!  I had found this solution with some google searches but it didn't seem to be working, but apparently I was just doing it wrong because I tried it again after your response and it worked, I must have had the capitalization wrong (it kills me how in some places it is such a stickler for capitalization and other places it doesn't care).

**Comment by darkphan** [comment]
Actually you need to set doTileDrops to true, there is no doBlockDrops

**Comment by Deylendor** [comment]
Yes it happens with certain mods blocks. For that reason I have a second "boat" ( 2 balloons and a helm ) ready to test how it all behaves when attaching the a new block I'm interested in putting inside my main airship. 

Results span from the whole ship despawning where I have to set doTileDrops to true again to outright hard server crashes. Once the vessel entity is build there are further things with modded blocks like, orientation not being preserved ( preventable by sticking to disassembling always in the direction you assembled, eg. always north ), or some blocks becoming invisible in their "entity state" ( storage drawers ).

Maybe some kind of "block probe" item for testing modded block for "compatibility" ingame. Would be better than loosing hard to craft blocks. Till such day we will have to cheat back our lost blocks and be vigilant on what to put on/inside the our vessels.
