### ISSUE TITLE
Shore Buffers not working

### ISSUE THREAD

**Issue by BluePyros** [darkevilmac/archimedes-ships-plus#19]
title says it all.  Shore buffers (and the attached blocks) are being included when trying to assemble a ship.

version beta-1 for both this and moving world.

**Comment by darkevilmac** [comment]
Wouldn't be considered a moving world issue, please label your issues correctly. These weren't implemented in the original, so they're not yet  implemented. Expect them to work in the next feature added build. This will happen after the 1.8 build.

**Comment by darkevilmac** [comment]
Fixed, 1.8 git version adds blacklist/whitelist blocks automatically.
