### ISSUE TITLE
Boats Despawning

### ISSUE THREAD

**Issue by VanillaBoi** [darkevilmac/archimedes-ships-plus#191]
Version: 1.12
Mod Version: 6.337

i understand that sometimes you can push the boats accidently but i've checked everywhere for my 2 that have disappeared and i cant find them, one of them was completely still and just disappeared in front of me.

**Comment by Deylendor** [comment]
Maybe you updated forge beyond 2356?

**Comment by darkevilmac** [comment]
Can't reproduce.
