### ISSUE TITLE
"See through" ships when using shader

### ISSUE THREAD

**Issue by Anonimon** [darkevilmac/archimedes-ships-plus#193]
- MC Version 1.12.2
- Forge 1.12.2

After assembling ships they get "invisible" while shaders are activated. They get normal if you travel far enough away from the ship or turn off shaders.

**Comment by Deylendor** [comment]
In my case I can see through the ship sometimes WITHOUT using any shader. It just flickers sometimes and the whole vessel entity become invisible depending on the angle I am looking around. I was able to decrease the flickering by positioning the helm a little bit "invards" the ship. My airship has walls build from balloons and I am driving from its interior, fully encapsulated and having vision only through glass block on the front and a line of glass blocks on the floor.

**Comment by darkevilmac** [comment]
Ya I don't expect this to work with any shaders unfortunately... Try with VBOs off, that's all I can recommend.

> In my case I can see through the ship sometimes WITHOUT using any shader. It just flickers sometimes and the whole vessel entity become invisible depending on the angle I am looking around. I was able to decrease the flickering by positioning the helm a little bit "invards" the ship. My airship has walls build from balloons and I am driving from its interior, fully encapsulated and having vision only through glass block on the front and a line of glass blocks on the floor.

This is related to culling in versions past 1.7, I've looked a lot and have yet to find a solution. Trust me when I say I've tried.
