### ISSUE TITLE
ID map corruption

### ISSUE THREAD

**Issue by ghost** [darkevilmac/archimedes-ships-plus#194]
- The version of the mod you are using: 5.335
- Your Minecraft version: 1.12.2
- Your Forge version: 14.23.0.2517

Here's some backstory on what this mod has done, so I can gradually get into the issue which has made me extremely angry to say the least:
Me and a friend had a modded server, this was about a month ago, one time the server crashed and I was unable to rejoin until my mate had come back and was able to open the server again.
When he opened up the server I was utterly devastated. Every single modded block had switched with another modded block, all the seared blocks from tconstruct switched with random blocks from Mr Cray fish's furniture mod, the smeltery was replaced with tons of lamps and baths... The paths I had outside were totally replaced with molten metals of some kind, and several other clashed; Online picture frames were replaced with flat coloured blocks... Every man-made or mod related thing essentially had their IDs switched.
We at the time assumed this was a big glitch, and the last backup we made was that day. Was kinda pissed off about that but we were able to switch into creative mode and fairly rebuild what was destroyed.
Anyway some time goes by, the friend I played on that server with just randomly stopped talking to me so I decided to make my own survival modded world with my own mods that I wanted to add.
So time goes on, I spend a lot of time on this world until suddenly, today, I was building a ship to drive around, and I went to place down the ship helm from davinci's vessels - It duplicated. I was confused, I opened up the GUI and another helm appeared in my inventory, so I just threw them into the water and the glitch resolved itself. OK. That was that over with.
But then this is what got to me, then I use xaero's minimap's waypoints to tp back home...
The game crashes... "Why?" I was so annoyed, however it was typical since earlier that week I had a similar crash when trying to take items out of a modded chest with a full inventory, so I just assumed it was somehow related... I was ignorant.
I reload the game to find that - once again; every modded block in that entire world had switched.

Here are some screenshots of the devastation:
http://prntscr.com/h9aakw
http://prntscr.com/h9aaqh
http://prntscr.com/h9ab0i

Due to the amount of models the game started to lag a lot as well.

This only happened once I started to use THIS mod. And in the server that I played on; there was ship helms on there as well. So I think that it's reasonable, and rational to come to the conclusion that this mod has basically obliterated my world because it only happened once I started to use this mod; to put it simply.

Please, please, PLEASE - try to fix this.
Here are a list of the mods I use:
http://prntscr.com/h9abrl

**Comment by exaskye** [comment]
This is a common form of world corruption, known as ID map corruption, and is not at all unique to Davincis Vessels. Forge makes it extremely easy to trigger this kind of corruption. (This, among other reasons, is why you should always keep frequent backups of modded worlds. Using [BTFU](https://github.com/elytra/BTFU) you can take backups every five minutes with no issue.)

We will need crash logs to look into this issue. You can find historical crash logs in .minecraft/crash-reports.

**Comment by ghost** [comment]
[crash-2017-11-12_00.10.39-client.txt](https://github.com/elytra/DavincisVessels/files/1464249/crash-2017-11-12_00.10.39-client.txt)
Above is the crash report (This was the time when it crashed when trying to tp home, then I reloaded the game to find the disaster)

Below are the last 3 logs as well.
[2017-11-12-2.log](https://github.com/elytra/DavincisVessels/files/1464251/2017-11-12-2.log)
[2017-11-12-1.log](https://github.com/elytra/DavincisVessels/files/1464253/2017-11-12-1.log)
[2017-11-12-2.log](https://github.com/elytra/DavincisVessels/files/1464254/2017-11-12-2.log)

**Comment by ghost** [comment]
Ps. The link you sent for the backup mod is for multiplayer? I play on singleplayer, the server I used to play on isn't up anymore so I moved onto singleplayer. Are they any similar things for singleplayer?

**Comment by exaskye** [comment]
That crash report seems to be during preInit, and is closely related to elytra/MovingWorld#48.

These are vanilla logs and contain very little information; please attach one of the fml-client-* logs instead.

EDIT: BTFU has experimental support for singleplayer, if I remember correctly. If not, singleplayer is on the roadmap and it's something I was asked to implement, though I haven't had time to do it.

**Comment by ghost** [comment]
OK here are the last 3 fml-client logs:
[fml-client-3.log](https://github.com/elytra/DavincisVessels/files/1464258/fml-client-3.log)
[fml-client-2.log](https://github.com/elytra/DavincisVessels/files/1464259/fml-client-2.log)
[fml-client-1.log](https://github.com/elytra/DavincisVessels/files/1464260/fml-client-1.log)

**Comment by exaskye** [comment]
:+1: - fml-client-1 contains the error that caused the corruption.

```
java.lang.IllegalAccessError: tried to access field net.minecraft.tileentity.TileEntity.field_145847_g from class com.elytradev.movingworld.common.tile.TileMovingMarkingBlock
	at com.elytradev.movingworld.common.tile.TileMovingMarkingBlock.func_189515_b(TileMovingMarkingBlock.java:215)
	at com.elytradev.davincisvessels.common.tileentity.TileHelm.func_189515_b(TileHelm.java:156)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:380)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:171)
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202)
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1006)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:324)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:224)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```

@darkevilmac

**Comment by ghost** [comment]
So what now? :(
Is there any way of recovering an older version of the save? Does forge make automatic backups?
The last backup I made was too far back.

**Comment by exaskye** [comment]
Unfortunately no, ID map corruption is irrecoverable if you loaded the world, as the tile entity data will be lost and blocks may have been copied around by being transformed into fluids. If the world isn't loaded after being corrupted, it is *theoretically* possible to transplant an old copy of the ID map and avoid the corruption, though it's risky.

**Comment by ghost** [comment]
When I noticed the world was corrupted, I made a backup instantly because the main part of the world was unloaded. They were in unloaded chunks. So is there a chance that copying the old id map to avoid the corruption to 'unloaded' chunks... like is that a possibility? I think it's worth a shot.

**Comment by darkevilmac** [comment]
What MovingWorld version are you on? This was fixed a while back when I removed the accesstransformers.

**Comment by ghost** [comment]
I was using "version: 1.12-1.333"

**Comment by darkevilmac** [comment]
Thats what I thought, https://minecraft.curseforge.com/projects/movingworld/files/2485041 342 has been out for over a month with this fix. Use that version in the future and make sure to keep backups with some sort of backup software.

EDIT: Also make sure to use the most recent davincis as well.

**Comment by ghost** [comment]
Thanks! Are there any software you can recommend? I mean I'm fine with just backing up the file every time I log off.

**Comment by darkevilmac** [comment]
https://github.com/elytra/BTFU (https://minecraft.curseforge.com/projects/btfu-continuous-rsync-incremental-backup) or AromaBackup are both fine.

**Comment by ghost** [comment]
Cheers.
