### ISSUE TITLE
Migration from 1.8.9

### ISSUE THREAD

**Issue by grannyte** [darkevilmac/archimedes-ships-plus#198]
I recently migrated a world from 1.8.9 to the 1.12.2 version and blocks are not up converted from the 1.8.9 version of the mod

**Comment by darkevilmac** [comment]
Transitioning between versions is never very smooth. Very little I can do here.

**Comment by grannyte** [comment]
well isn't it because the name of the mod changed? 
my world has many blocks named archimedes ship plus and non named Davincies

i think in the past you added aliases to allow for changing version or migrating from previous verisons

**Comment by darkevilmac** [comment]
This was removed after the version gap grew, if you run with the mod in a previous version (the first version with the davincis name) things *should* convert over.

**Comment by grannyte** [comment]
what was the last version with the upconversion? I guess i could build my own intermediary step to convert blocks
