### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by alphapapa** [darkevilmac/archimedes-ships-plus#199]
Hi there,

I know you're not the originator of the Archimedes mod, but I want to thank you for picking it up and carrying it forward.  I've been playing Minecraft with some friends on a private server for a while now, and I've always wished that we could load up a ship with resources in a far-away biome across the sea, and bring them home to our base, without having to do silly things like drag donkeys behind our boats.  I hadn't messed with Minecraft mods before, but I finally decided to give this a try, and it's really amazing how well it works!  This opens up a whole new world of adventures!  And I'm very glad that I'm able to use it with the current version of Minecraft.

Please keep up the great work!

**Comment by darkevilmac** [comment]
Not really an issue but you're very welcome!
