### ISSUE TITLE
Water Trench Bug

### ISSUE THREAD

**Issue by ThatPolishKid99** [darkevilmac/archimedes-ships-plus#2]
this is a long standing problem, that has been mentioned on Balkondour's Original Thread, and i found a quick fix solution, but its not too effect
the Bug itself is that when you have a 1x1 block extending past what i guess you could call the "perimeter" of your ship, a trench of air in water sometimes forms along the sides of the ship 
kind of hard to see these photos, but the second one shows the hole 
![2014-08-09_13 56 59](https://cloud.githubusercontent.com/assets/10103417/6339542/876f7368-bb7c-11e4-9069-759bec6f310b.png)
![2014-08-09_13 58 02](https://cloud.githubusercontent.com/assets/10103417/6339546/89570d8a-bb7c-11e4-90fd-54edd8e6a7cb.png)

**Comment by darkevilmac** [comment]
ISSUE MOVED: https://github.com/darkevilmac/MovingWorld/issues/9
