### ISSUE TITLE
Suggestion: Invert banking for airships vs. water ships

### ISSUE THREAD

**Issue by alphapapa** [darkevilmac/archimedes-ships-plus#200]
Hi,

I've been enjoying making airplanes and boats, but if the ships bank outward, the airplanes do too.  So I changed the bank to a negative number, which fixes the airplanes, but now ships will bank inward too, which only makes sense for e.g. speedboats, not large ships.

It would be nice if there were an option to invert the bank angle for aircraft, that way each one could bank correctly.

Thank you for your work on this mod!

**Comment by alphapapa** [comment]
I've been thinking about this some more, and I wonder: what do you think about adding basic support for different types of vehicles?  For example, if there were an aircraft type, with airplane and helicopter types inheriting from it, the aircraft type could bank in rather than out, and require a different balloon ratio.  That way, airships and seaships could keep their behavior rather than interfering.

**Comment by darkevilmac** [comment]
Eh, accuracy isn't my top concern. I'm more focused on usability and ease of use. The way it works right now is intuitive for the vast majority of users.
