### ISSUE TITLE
Make the player not fall through the ship after dismount

### ISSUE THREAD

**Issue by Niko-sk2x** [darkevilmac/archimedes-ships-plus#202]
That would at least make the "shift to dismount" a bit less deadly for those used to space=up, shift=down.

**Comment by darkevilmac** [comment]
Enable disassemble on dismount in the configuration file.

**Comment by Niko-sk2x** [comment]
It's a server. I don't directly control the config. And not everyone wants to actually "disassemble" it when getting off the ship
