### ISSUE TITLE
Add Glowing Shore Buffer

### ISSUE THREAD

**Issue by CursedFlames** [darkevilmac/archimedes-ships-plus#206]
I think it would be useful to have some form of light-emitting shore buffer, because when a landing area isn't lit up mobs spawn, and when it is the airships stick to the lights, which defeats the purpose of a landing area. Perhaps crafted using shore buffers and glowstone?

**Comment by Lurmey** [comment]
I don't see why you can't have a sort of grid or rail system for the airship to rest on, with the layer below that being the actual platform which has the glowstone or other light sources integrated.

**Comment by darkevilmac** [comment]
As mentioned above, just add lighting around the area. Seems unnecessary.
