### ISSUE TITLE
Ship doesn't detect more then one passenger seat

### ISSUE THREAD

**Issue by Nouwan** [darkevilmac/archimedes-ships-plus#207]
mod version: 0006
minecraft version: 1.10.2
forge: 1.10.2-12.18.3.2185

When having more than one seat on your ship/air balloon. only one player can be seated. I'm aware of the fact that this is fixed in 1.12 however we do still use the 1.10 version and would like the bug fixed. 

I could if needed fix the bug myself and open a pull request but it would be very helpful to have at least some leads to how and where the bug occurs since I don't know the codebase.

**Comment by darkevilmac** [comment]
1.10 is no longer supported.
