### ISSUE TITLE
Not an issue as such - more of a querry on Nether

### ISSUE THREAD

**Issue by ElayCarver** [darkevilmac/archimedes-ships-plus#208]
I  ve installed and now playing around with version 12 .
Amazing mod , just wondering if : 
a it si possible to build an airship in nether ?
b is an airship aible to traverse Nether portal?

**Comment by CursedFlames** [comment]
You can build airships in the nether.
Airships can travel through nether portals (if they can fit), you just have to dismount for them to go through, since you can't go through portals while riding something.
