### ISSUE TITLE
Using blacklist

### ISSUE THREAD

**Issue by notchriss** [darkevilmac/archimedes-ships-plus#21]
I'd like to enable and disable some blocks using blacklist, i.e. list of blocks that will not be added to a ship when assembling. The list goes like

S:forbidden_blocks <
minecraft:dirt
minecraft:grass
...
use_whitelist=false

minecraft:water and minecraft:flowing_water are in the black list so they are not added to the ship. But liquid redstone is not in the blacklist, and yet it's not added to the ship either, flowing or not. Is it because any liquid is excluded by default? It would be really nice if we could have nuclear reactors on the ships.

Also, I understand the format is probably mod_name:item_name, but how exactly does it work? How shall I provide mod name, i.e. with spaces or without, is capitalization important, where shall I find the "technical" item's name?

Blocks I want to disable are Thaumcraft 4 nodes, since now they can be moved along with ship very easily, rendering Thaumcraft's node moving mechanic pointless.

Blocks I want to enable are basically all the liquids other than water that could be used to cool Big Reactors reactors (liquid redstone, liquid ender and such, whatever their correct names are). 

Thanks in advance for your help!

**Comment by darkevilmac** [comment]
Fluids are disabled on ships because they can cause building issues, that's why they won't assemble with your ship. For item names, I find just using tab complete with /give works fine to find what I need. The format that forge uses is modid:unlocalizedName for example, buildcraft:engineStone(don't think this is right just an example)

**Comment by darkevilmac** [comment]
Oh, also this is not an archimedes ships issue so I'll be closing it. Please open an issue in www.github.com/darkevilmac/movingworld
