### ISSUE TITLE
[MovingWorld] FPS drops: 120 -> 0,5

### ISSUE THREAD

**Issue by PumaBlack** [darkevilmac/archimedes-ships-plus#212]
Although probably nobody answers again anyway:

I have massive FPS drops, if the ship is a little bigger (about 9000 Blocks). I do not mean from 120 FPS down to 60. No, the FPS goes down to 0,2 or 0,5 :/ (that it disappears is already normal, but i still riding "some invisible thing")
Minecraft runs with about 5 - 8 GB RAM. Graphics as low as possible. No other Programs, that could use the RAM.

    davincisvessels-1.12-6.340-full.jar
    movingworld-1.12-6.342-full.jar
    1.12.2-forge1.12.2-14.23.1.2587

Thanks in advance, but i think this mod was abandoned by the dev. :(

**Comment by Ravin890** [comment]
Log would help people try to figure it out
