### ISSUE TITLE
1.12 Release

### ISSUE THREAD

**Issue by alexisab** [darkevilmac/archimedes-ships-plus#214]
First, thank you to keep this mod uptodate !

I'm totally new to minecraft modding and I havn't seen a release for the 1.12 version. Do you plan to add it to the github repo ? Or should I compile it ?

Thanks !

**Comment by calloatti** [comment]
https://minecraft.curseforge.com/projects/davincis-vessels/files?filter-game-version=1738749986%3A628

**Comment by alexisab** [comment]
Thank you, and : 
1 - Is it possible to install this mod on a server ?
2 - If yes, do players also need to install the mod locally?

Thank for your help !

**Comment by Ravin890** [comment]
Most mods can be put on servers, and unless stated on their page, all players must install the mod to join server

**Comment by alexisab** [comment]
Thanks ;)
