### ISSUE TITLE
Submarine passengers do not have buffs

### ISSUE THREAD

**Issue by yangxuilyx** [darkevilmac/archimedes-ships-plus#219]
When I dive with my friend, the passenger does not have a buff. Is this a bug or a setting? Can it be repaired? Thank you

**Comment by darkevilmac** [comment]
Missing details on the mod versions and minecraft versions. This shouldn't be happening if you're on the most recent builds of 1.12. If it is then post a new issue or respond to this one with the needed information and I'll reopen it.

**Comment by AymenQ** [comment]
1.12-6.340, still seems to be happening.
