### ISSUE TITLE
Cannot start Minecraft, DV crash

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [darkevilmac/archimedes-ships-plus#222]
- Mod Version: 6.340, version of moving world: 6.342
- Minecraft Version: 1.12.2
- Forge Version: 14.23.2.2625
- https://gist.github.com/pPkMnh4to8994h/bc98036f1a6cc546c51d3ccc9f1d8e73 (crash report)
- https://gist.github.com/pPkMnh4to8994h/116a55e3b3c972a539240f604d80cfec (fml-client-latest)
- LiteLoader is present, just in case if this helps you.

Crash occurs right after loading game.

**Comment by pPkMnh4to8994h** [comment]
If you delete LiteLoader, the problem will go away.
You should add remind somewhere, that LiteLoader don't like Davinci's Vessels very much.

**Comment by darkevilmac** [comment]
I most likely need to update Mixins, it's been a while.

**Comment by darkevilmac** [comment]
See https://github.com/elytra/DavincisVessels/issues/168
