### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by BboyApache** [darkevilmac/archimedes-ships-plus#228]
Hi, I was just playing my ModPack with Davincis Vessel and when I configured it to be able to create more than 2048 Blocks > Assemble ship > Mount > then I crashed. Everytime I try to log in, I get the "Game Crash" Problem over and over and I can't get into my world. =(

Mod Version: 
davincisvessels-1.12-6.340-full

Minecraft version:
1.12.2 Java Edition

Forge version:
forge1.12.2-14.23.2.2611

This was all the report it showed me when I click "show details". It did not do anything when I click on "view crash report".

The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:stone, properties=[variant]}

**Comment by Lurmey** [comment]
You can find the crash report in your modpack files. Find wherever your modpack is installed (probably within the files of whichever launcher you're using, Twitch/Technic/ATLauncher etc), head to the instance of your modpack and upload the latest file in the crash-reports folder.

**Comment by Lurmey** [comment]
And actually, within the crash report it'll tell you which block is the ticking block that's causing the crash. It should also tell you the exact coordinate location of said block and the region file it's stored in. Using all this information, you should be able to find and delete the block in NBTExplorer. If you have no idea how to do this, search and add "Lurmey" on the Twitch desktop app, if you have it. I'll walk you through how to do it.

**Comment by darkevilmac** [comment]
I'm going to need a full crash log, closing until that's made available.
