### ISSUE TITLE
Crates do not properly hold pets

### ISSUE THREAD

**Issue by MrSmite** [darkevilmac/archimedes-ships-plus#229]
**Mod:** 1.7.10-1.8.1
**Minecraft:** 1.7.10
**Forge:** 10.13.4.1614-1.7.10

**Issue:**

Crates do not properly hold tamed wolves, they disappear when the ship is assembled and take fall damage when the ship is disassembled.

**Details:**

I built a small ship out of planks, stairs and fences and added four crates to the back. I then used a lead to bring two tamed wolves onto the crates and once they were "stuck"  I assembled the ship.

All was fine at first but either the height or speed was too much because they suddenly vanished (but I could hear them barking). I aligned and disassembled the ship in the air and they reappeared without issue.

The problem now is that whenever I assemble the ship, they fall off and a message appears that they fell from a great height. It seems the crate will no longer retain them once the ship is dis/reassembled. After a few times of them falling, the simply won't reappear on the ship at all (if it is disassembled in the air).

**Additional Notes:**

I am using the mod [Doggy Talents](https://minecraft.curseforge.com/projects/doggy-talents) which changes the entity to a "dog" but given the description of the crate, it should work with any living entity.

I also tried an older version of 'Archimedes Ships' for 1.7.10 but it exhibits the same behavior. The crate seems to not function properly once an entity becomes bugged and falls off the ship. Picking up the crate and placing it down again doesn't seem to reset it either.

**Comment by darkevilmac** [comment]
1.7.10 is no longer supported.
