### ISSUE TITLE
Submarine Crash 

### ISSUE THREAD

**Issue by mxnmnm** [darkevilmac/archimedes-ships-plus#230]
- The version of the mod you are using (e.g. 2.0.0a4)
davincisvessels-1.12.2-6.340
- Your Minecraft version (e.g. 1.11.2)
1.12.2
- Your Forge version (e.g. 13.20.0.2252)
forge-1.12.2-14.23.3.2676
- The crash report or log, uploaded to gist.github.com
https://gist.github.com/mxnmnm/6d69ee07b85bf52429f9dd0df7a85510

-Extra notes
This happened after I clicked on the submerse button.  I was able to get back into the world but the ship deleted itself.

**Comment by darkevilmac** [comment]
Looks like I forgot some null itemstacks, fixed locally will be on github in a minute.
