### ISSUE TITLE
Visual Glitch?

### ISSUE THREAD

**Issue by BlitzHayato** [darkevilmac/archimedes-ships-plus#233]
1.12.2
mod version 1.12
1.12.2-forge1.12.2-14.23.3.2677

I am experiencing an odd visual glitch while flying the airship or any ship in general. If I'm not looking in very specific angles the ship vanishes.  It only seems to occur when actually mounted to the ship. I've also determined that it occurred AFTER I attached forge micro blocks half glass slabs. Assuming an incompatibility. Upon mounting the ship with those blocks attached, they all vanished but the ship started acting as stated above. Just thought I would bring it to your attention and the attention to anyone who might try it.

Love your mod!
Best,
Blitz

**Comment by Twilix01** [comment]
I have the same issue, have also experienced it with optifine installed (with and without VBOs) and with it uninstalled.  It makes it difficult to judge if you can fit your ship into an area.

**Comment by MonsieurPlun45** [comment]
Bonjour,
j'ai aussi ce même problème mais avec aucun bloc d'aucun autre mod ! Si vous avez trouvé une solution, écrivez ici s'il vous plaie

**Comment by darkevilmac** [comment]
Duplicate Issue, this is a vanilla problem. Not much I can do besides hacking around the entity culling (which I don't plan on doing any time soon)

https://github.com/elytra/DavincisVessels/issues/227

**Comment by ghost** [comment]
i have a similar problem
