### ISSUE TITLE
Carpenter's Blocks don't keep their configuration on assembling

### ISSUE THREAD

**Issue by katzenpapst** [darkevilmac/archimedes-ships-plus#24]
Sorry, I just now have seen your "bug reports in the thread will be ignored". 

Anyway: Stuff like Slopes from Carpenter's Blocks don't keep their orientation or texture when the ship assembles:

Before: http://files.katzenpapst.de/files/2015-05-29_19.29.37.png

After: http://files.katzenpapst.de/files/2015-05-29_19.25.04.png

**Comment by darkevilmac** [comment]
I'm able to replicate this, main issue is that they should be working fine. Models from other mods seem to work fine from what I've tested. There's always a possibility that Carpenter's Blocks render with something other than a TESR, but if that's the case I can't really do anything besides making a custom exception for that mod.

Also, this is more of an issue with MovingWorld. I'll leave this issue open here just for the sake of time, but in the future just be sure to know that rendering and ship assembly/disassembly is MovingWorld. Control, and blocks are in this mod.

**Comment by katzenpapst** [comment]
Hm, but your forked your stuff from the original mod, and it definitely works there. Or is MovingWorld a complete re-implementation?

**Comment by DPxKnightxZero** [comment]
Yeah Carpentures blocks worked great until the most recent versions.

**Comment by darkevilmac** [comment]
This should be fixed in 1.8, even though they haven't updated.

**Comment by katzenpapst** [comment]
So, no fix for 1.7.10? :/

**Comment by DPxKnightxZero** [comment]
I will only use 1.7.10 until 1.9 comes out because its going to be close to the final release.

**Comment by darkevilmac** [comment]
Unfixed for 1.7, due to lack of stable 1.8 build this needs to be fixed.

**Comment by DPxKnightxZero** [comment]
Not quite sure I follow your comment anyways I too am waiting for forge 1.8 to be more stable and I agree with you its not good to stay outdated. I am sorry if it seemed I was yelling at you.

**Comment by darkevilmac** [comment]
The MovingWorld 1.8 builds are alpha, they're not overly stable. I'm surprised they even work, I barely understand much of the code. My conclusion is that 1.8 builds are made of magic.

**Comment by DPxKnightxZero** [comment]
Hahahahahahah I would agree to that!

**Comment by DPxKnightxZero** [comment]
We just have to wait for the grand wizard king of minecraft to explain things a bit more.
