### ISSUE TITLE
Unknown Block duplicate crash.

### ISSUE THREAD

**Issue by JakeGamer** [darkevilmac/archimedes-ships-plus#26]
Hello, I get this crash with the 3 mods, Archimedes Ships, AS+, and moving world.

http://pastebin.com/mspvmgFT

I tried deleting the configs, Archimedes ships doesn't let you change block ids.
I know your mod is the problem since I test ran Archimedes ships and moving world together, they worked just fine.

I'm using the latest builds of the mods and forge.

**Comment by darkevilmac** [comment]
-.- don't run with all 3 mods installed.

Step 1. backup your world and config files.

Step 2. remove the old archimedes ships mod.

Step 3. install MovingWorld as well as ArchimedesShipsPlus

**Comment by JakeGamer** [comment]
I'm sorry for being an idiot, Thank you! ^_^
