### ISSUE TITLE
vessel embedded inside a hill

### ISSUE THREAD

**Issue by PatriceBoivin** [darkevilmac/archimedes-ships-plus#269]
Using forge 14.23.5.2808 w JRE 8u201 and Minecraft 1.12.2
dv 1.12-6.340
moving world 1.12-6.342

with many other mods....

My son created a ship, sat on the seat, tried moving the boat and "it started freaking out".  He went backward, tried to turning, it started working but when he tried going forward it didn't work.
He left the boat to see what happened and saw that it was stuck inside the hill.

When we enter the boat we start taking damage.  When we press shift-L to leave the boat we are ejected some distance and land in the water.  If we can do that in time... we take damage pretty quickly while in the ship.

We cannot destroy the ship, the command doesn't work while we are in it and taking damage.

If we try breaking the blocks around the boat we cannot.  If we R-click on blocks associated with the boat we are sucked into it.

Logged in as myself I noticed that if I look just next to the edge of the ship the ship disappears, but when I look at one of the blocks it covers it reappears.  Almost as if the game believes block positions overlapped by the ship's blocks contain two blocks in the same spaces (?).

Is it possible to move a ship manually using config files somewhere, maybe if we move it to a location where it won't overlap existing dirt and stone blocks the game will calm down?

**Comment by darkevilmac** [comment]
If you can't disassemble your ship by normal means, then use /dvdisassemble with the argument 'overwrite'

**Comment by PatriceBoivin** [comment]
I tried, it says "cannot disassemble ship here".

Thank you for suggesting something though.

I thought perhaps what we need are anchors, but my son says they don't exist in the newer version (?).  I am not even sure they would solve the problem though, his ship is not a flying ship, it was only intended to float on water.  Now it's embedded in a hill like the Ark on Mount Ararat

**Comment by Szablya** [comment]
I had this issue a long time ago in an older version. My ship was very large (wide and long rather than lots of blocks. Was it an unusual size or shape? My solution was to remove the mod and restart the game and then re-install the mod. This deleted the misbehaving ship and anything else from the mod.

**Comment by PatriceBoivin** [comment]
thank you Szabiya, that worked.
