### ISSUE TITLE
Height limit of 256 chops off blocks when anchored above

### ISSUE THREAD

**Issue by AwakenedSoul** [darkevilmac/archimedes-ships-plus#27]
When anchoring above 256 blocks, all blocks 256 and up and chopped off the ship and disappear.

**Comment by TehStoneMan** [comment]
256 is the build limit for Minecraft itself, so there can't be any blocks above that height. Maybe needs a disassemble height limit so that you can't disassemble a ship if any part of it is above 256.

**Comment by darkevilmac** [comment]
Pretty much yeah. This is a MovingWorld issue by the way, so I'm closing
this issue and I ask that you open a new issue in the MovingWorld repo.

**Comment by darkevilmac** [comment]
Well no issue was opened, it's patched out in the 1.8 build anyway though.

**Comment by AwakenedSoul** [comment]
Yeah sorry about that, I'm actually in a middle of finals week so I haven't had time for much of anything
