### ISSUE TITLE
Client crashes when assembling vehicule

### ISSUE THREAD

**Issue by RemiBraizet** [darkevilmac/archimedes-ships-plus#282]
Hi, as the title say, my client crashes when assembling a vehicule.

- Mod version: davincisvessels-1.12-6.340-full
- Minecraft version: 1.12.2
- Forge version:  14.23.5.2838 for MC 1.12.2
- Crash report: https://gist.github.com/Remaetanju/accffb346486b09bb356161997a4d250

all was working fine, but i added some mods recently:
millenaire mod
MJRlegends
tropicraft
extraplanet
hwyla

and maybe (but i don't see why it could be them)
betterhud
village info
journeymap

but i don't see any obvious reason why this would cause this

**Comment by CalmBit** [comment]
It definitely does seem to be an error with BetterHud - my advice, for now, would be to remove it and see if the crash persists.

**Comment by RemiBraizet** [comment]
You were 100% right, i assume BetterHud tries to read HP and other stats to display it, to the player.

**Comment by CalmBit** [comment]
It's not necessarily an error _in_ BetterHUD, perse, but rather an incompatibility. I'm not sure which side is causing the error straightaway, but I'll do some digging.

EDIT: The stacktrace is shifted a little bit (by like +2 lines from what the stacktrace says vs the actual file), but it seems to be a problem accessing the `offset` property on AssembleResult?

(cc @darkevilmac)

**Comment by darkevilmac** [comment]
Not sure why this is happening, no real reason the tile should be mentioned for any sort of Gui rendering...

I specifically store a custom item model to avoid this.

**Comment by CalmBit** [comment]
The author of BetterHUD has made a fix on his end, and I'm assuming something is unorthodox about the way they were handling TE item stacks, or something.

Anyway, closing this issue for now.

**Comment by CalmBit** [comment]
As a quick aside, I tested Ctrl+Pick Block w/ DV/MW and no problems or crashes were encountered. Therefore, I can only readily assume that it is indeed a problem on BetterHUD's end.
