### ISSUE TITLE
How to increase max ship size

### ISSUE THREAD

**Issue by PlsHalpme** [darkevilmac/archimedes-ships-plus#286]
- Davinci's Vessels 1.12-6.340
- Minecraft 1.12.2
- Forge 14.23.5.2838

Tried to increase the max_chunk_blocks through the mod options for davinci's vessels, but it keeps reseting the max to 2049. Is there any work around for this? I've searched all over and can't find the answer for this version. And can't find the config options for moving world

-Thank you for your time and awesome work!

**Comment by MineMike** [comment]
Hey Pls, I just tested my current build is running at 2710 blocks. You need to change the following values in .Minecraft/config/davincisvessels.cfg

I:max_chunk_blocks=4096

AND in .Minecraft/config/ArchimedesShipsPlus.cfg

 # The maximum amount of blocks that a mobile ship chunk may contain.
    I:max_chunk_blocks=4096
 
I'm also fairly certain it needs to be a number divisible by 2 so 2048, 4096, etc.

Be forewarned though, I'm currently having a movement snap issue with this vessel, not sure what its related to yet, but it may be ship size. 

Moving world has a config file in the same place, but I've only ever added or subtracted blocks from the allow/disallow list.

**Comment by PlsHalpme** [comment]
"> Hey Pls, I just tested my current build is running at 2710 blocks. You need to change the following values in .Minecraft/config/davincisvessels.cfg
> 
> I:max_chunk_blocks=4096
> 
> AND in .Minecraft/config/ArchimedesShipsPlus.cfg

Thank you for the advice Mike. What program are you using to view the config files? When I open them they don't have numerical values and are nearly gibberish with random symbols. Finally do you need to have archimedes ships plus in order to run the mod correctly? I think my server moderator only has Davinci's Vessels and Moving Worlds downloaded in our mod pack.

**Comment by darkevilmac** [comment]
You shouldn't need to adjust anything in the archimedes config, Davincis and MovingWorld don't make those config files, if they do then I've screwed up something quite bad.

You need to modify the MovingWorld config as well as the Davincis config, you're correct that it will work better if it's a multiple of 2048, however it should still work even if it's not.

**Comment by PlsHalpme** [comment]
> You shouldn't need to adjust anything in the archimedes config, Davincis and MovingWorld don't make those config files, if they do then I've screwed up something quite bad.
> 
> You need to modify the MovingWorld config as well as the Davincis config, you're correct that it will work better if it's a multiple of 2048, however it should still work even if it's not.

Thank you darkevilmac, but what program are you using to open the files. When I use notepad it looks like the files are unreadable and its hard to find the right script to input values. Any advice there?

**Comment by PlsHalpme** [comment]
I extracted the java file and found the config options in the com/elytradev/movingworld/common/config/mainconfig but cannot find the script for max block and when I do the same for Davincis I can find the I:max_chunk_blocks but the script isn't a number its Æ which is foreign to me. In other words. Can someone explain this like I'm 5? lol

**Comment by PlsHalpme** [comment]
oof I have way over thought this. If anyone has this same issue and is using a twitch mod pack such as FTB Builders Paradise then you need to open the folder location through twitch, scroll down to the config folder, and find the mods in there in order to change the values. 

I still don't see max_chunk_block for Moving Worlds but I think I can find it now. 

Thanks for all the help. I was trying to do this like hackerman.

**Comment by PlsHalpme** [comment]
Rip, those were CFG files that led to internet explorer links of the code that I couldn't retype values in. One step forward and two back

**Comment by MineMike** [comment]
Darkevilmac, that may be my bad, prior config files failed to clean. 

Pls, I open those config files with notepad. 
1.Right click on the file and go to properties.
2. under "open with" click the change button and select notepad. 
3.Apply/Ok.
4. open the file and make your edits, file-save. 

Never run the mod on a server, might be something your admin has to configure.

**Comment by PlsHalpme** [comment]
That's the one! Same locations I said before. I just didn't right click and open the CFG files with notepad. Thanks a million!

**Comment by Dickovski** [comment]
I built a ship that is quite a bit bigger than 2048 and got the Overflow error message. Found the config file (as suggested elsewhere), modified it to 4096 but found the same problem.  Then I discovered that you can change the config internally from Mod Options.  Changed it to 4096 in Mod Options, but now I get Error, with a message to check the console log. I can't find a 'console log' to check it but the latest.log in logs mentions davincisvessels but  cannot see anything that might be an error.  I've just tried creating a block of stone using fill, this came to 3456 blocks, it gave the overflow error with, changed the Max_Chunk_Blocks to 10000 to be safe and it worked.  However, create a bit bigger object, I tried 3888 blocks,  and Error comes up.  A memory limit of some sort?

**Comment by darkevilmac** [comment]
As noted above, the configuration files are in the config directory of your minecraft instance. You'll want to edit the MovingWorld.cfg file to change the max ship size, you also need to enable iterative assembly.

These are plain text files and can be modified in just about any text editor.

As an addendum, for the most part larger sized vessels should still function as expected. However the default size is set that way for a reason, so please note that things may become unstable. So *please* create world backups.

Closing this issue.

**Comment by Dickovski** [comment]
No sign of a MovingWorld.cfg file anywhere!

**Comment by darkevilmac** [comment]
At the root of your configuration directory there is a folder called MovingWorld, inside that directory there are two configuration files.

You'll want to set "Use Iterative Algorithm" to true.

**Comment by stdntuvmath** [comment]
@darkevilmac  - I know this thread is old but I agree with Dickovski. There are no searchable .cfg files in the folder called com\elytradev. That goes for either the davincisvessels folder or the movingworld folder. Further, the first folder inside com\elytradev\movingworld is called repackage then it gets worse from there:

com\elytradev\movingworld\repackage\com\elytradev\concrete

seems to be where all the movingworld class files are held. There are no .cfg files and all I see are java class files. I think it would be better for everyone if you would bring back the .cfg files you allegedly had in 2020 so that we can play the game properly. I would sure appreciate it. I've scoured your class files for the limit 2048 and can't find it anywhere.
