### ISSUE TITLE
New Release please

### ISSUE THREAD

**Issue by xNissX233** [darkevilmac/archimedes-ships-plus#288]
Please make a new release of this and movingworld for us mortals who just want to play the mod and don´t know how to compile this. The curseforge page is not updated anymore and I want to play this mod in new minecraft versions.

**Comment by darkevilmac** [comment]
There's no release on newer versions on CurseForge because it's not currently stable. Collisions aren't working properly and controls are quite glitchy right now.

I'll publish a build on curse once it's ready for release.
