### ISSUE TITLE
Suggestion: Add Tire-Blocks for cars etc.

### ISSUE THREAD

**Issue by lucom** [darkevilmac/archimedes-ships-plus#3]
It is possible to "sail" a light ship on the ground, which is similar to driving.

Maybe you could add some kind of logic that allows climbing half slabs when there are tires attached to the bottom of the vehicle.

Just try sailing a very small ship on a flat area (like a desert etc.).

**Comment by darkevilmac** [comment]
This can be done after the transfer of core code. After the code is transferred things like this should be easy.

**Comment by ajthemacboy** [comment]
I've wanted this for so long! I seriously can't wait.

**Comment by darkevilmac** [comment]
Sorry for the wait, still not in but I'm currently rewriting MovingWorld, so I'll see what happens after that.
