### ISSUE TITLE
Is this mod still being updated? 

### ISSUE THREAD

**Issue by ninest** [darkevilmac/archimedes-ships-plus#308]
Sorry for putting this as a GitHub issue. I wasn't sure where else to ask.

**Comment by Timeslice42** [comment]
I'd guess that's a no.

**Comment by noopynolife** [comment]
Shame really

**Comment by ninest** [comment]
Yeah, this was a great mod

**Comment by darkevilmac** [comment]
That sure is a lot to extrapolate out of no response on something that shouldn't be a GitHub issue.

None of my mods are abandoned, I've been doing rewrites of a lot of code behind the scenes and will make proper commits once I'm happy with them.

Closing.

**Comment by ninest** [comment]
@darkevilmac I'm sorry for making this issue. I look forward to seeing updates when they're ready!

**Comment by Timeslice42** [comment]
@darkevilmac And just what else would you expect us to extrapolate from an issue that had no response for 30 days on a mod that hasn't seen commits in months or a release in years?

**Comment by noopynolife** [comment]
@Timeslice42 Ah no need to continue attacking one another. I'm just glad to hear the mod is coming back!

@darkevilmac any indication on what minecraft version you are working on at the moment?

**Comment by darkevilmac** [comment]
> @darkevilmac And just what else would you expect us to extrapolate from an issue that had no response for 30 days on a mod that hasn't seen commits in months or a release in years?

That I've been busy with my job and don't want to release something that doesn't work properly? I have taken breaks in the past and when I did I would let people know and try to have someone maintain things while I was busy.

Modding is a hobby and I'm just one guy working on just under five projects at any given time. I don't have a PR team to give updates on my progress all the time.

**Comment by darkevilmac** [comment]
> @darkevilmac any indication on what minecraft version you are working on at the moment?

Just like normal I target the latest forge release, if a new version comes out before I can publish a release then I shift development over to that version.

So right now I'm targeting 1.15, main issue I'm fighting with right now is some fixes to ship collisions.

Minecraft only likes bounding boxes that never rotate, so I'm trying to implement some fixes so ships actually hit walls and things a bit more realistically

**Comment by Parciwal** [comment]
> 
> 
> > @darkevilmac any indication on what minecraft version you are working on at the moment?
> 
> Just like normal I target the latest forge release, if a new version comes out before I can publish a release then I shift development over to that version.
> 
> So right now I'm targeting 1.15, main issue I'm fighting with right now is some fixes to ship collisions.
> 
> Minecraft only likes bounding boxes that never rotate, so I'm trying to implement some fixes so ships actually hit walls and things a bit more realistically

The create mod managed to do it, could you look at what they did to get inspiration?
