### ISSUE TITLE
1.8-ALPHA-2-HFX

### ISSUE THREAD

**Issue by kreezxil** [darkevilmac/archimedes-ships-plus#32]
At least two issues:
1. items from the mod are not grouped in either a creative panel or an NEI panel for easy identification
2. and this one is a biggie, when falling off of the ship, possibly with dismount, the ship keeps moving. In a void world this is bad. 
3. Also, there appears to be no legit way to remount the ship if it is moving and you are not on it.

**Comment by darkevilmac** [comment]
1: Not an issue that's resolvable. FML chooses my block ids, not me.

2: Also not an issue, if you look in the code for the ships you can see that ships are pushable if they're not mounted. That's just how they function.

3: Chase it down, right click.

**Comment by kreezxil** [comment]
How do the other mod have nice panels? I made a decorative one without even trying to hard and NEI put out on a panel.

-----Original Message-----

**Comment by darkevilmac** [comment]
Can you reword that? I don't really understand what you're trying to say.

**Comment by kreezxil** [comment]
In regards to #1, I know that forge sets the ID. However, you can still group your items into a panel. As an example, my mod of which you can find here at Github, all of its items are clearly identified under one panel in NEI. Further I am not the awesome programmer that you are so I don't understand why your items aren't similarly grouped.

-----Original Message-----
