### ISSUE TITLE
mount ship, coal blocks fall out of steam engines

### ISSUE THREAD

**Issue by Ghosty366** [darkevilmac/archimedes-ships-plus#330]
- 6.355
- 1.12.2
- 14.23.5.2854
- no crashes
every time I mount the ship the coal blocks fall out of the steam engines

**Comment by Jay420blaze** [comment]
happens with me and my friends too :(

**Comment by CatacombNoop** [comment]
This is also happening with chests. When I assemble my ship, all items fall off

**Comment by darkevilmac** [comment]
Is this a new issue or was it occurring with previous Davincis and MovingWorld builds as well?

**Comment by CatacombNoop** [comment]
Just tested it on 
"davincisvessels-1.12-6.337-full.jar" and "movingworld-1.12-6.342-full.jar"
Items/Coal are not dropping from chests/steam engine

**Comment by Ghosty366** [comment]
> Just tested it on
> "davincisvessels-1.12-6.337-full.jar" and "movingworld-1.12-6.342-full.jar"
> Items/Coal are not dropping from chests/steam engine

6.340 is fine too, which is the latest release

**Comment by darkevilmac** [comment]
Looks like this is related to the change made here, will investigate further.

https://github.com/TridentMC/MovingWorld/commit/d54cdc68c9b8f731b1ca445649b53c923c731d9e

**Comment by Jay420blaze** [comment]
"davincisvessels-1.12-6.340" and "movingworld-1.12-6.352"
Coal is being dropped and so are chests, so guessing its something with the newer release

**Comment by Ghosty366** [comment]
it is 6.355 it's not any other version

**Comment by darkevilmac** [comment]
Currently building a fix, could someone test this and confirm the issue is resolved? If it is then I'll publish a new build on Curse.

Oh, and this is a particularly aggressive change, so backup your world in case something terrible happens (it shouldn't but lets not take any chances)

https://ci.tridevmc.com/job/TridentMC/job/MovingWorld/job/1.12/5/

**Comment by Jay420blaze** [comment]
> Currently building a fix, could someone test this and confirm the issue is resolved? If it is then I'll publish a new build on Curse.
> 
> Oh, and this is a particularly aggressive change, so backup your world in case something terrible happens (it shouldn't but lets not take any chances)
> 
> https://ci.tridevmc.com/job/TridentMC/job/MovingWorld/job/1.12/5/

Seems to work perfectly, didnt have any issues! Thank you so much :)

**Comment by darkevilmac** [comment]
Pushing the changed build to curse.
