### ISSUE TITLE
how to change the density

### ISSUE THREAD

**Issue by Radyfil** [darkevilmac/archimedes-ships-plus#333]
how to change the density of the ship to make it more submerged in the water.

**Comment by FDammer** [comment]
You need to adjust density of blocks your ship is mainly made of
Let's say **for example** it is made of Lapis Lazuli:

go to .minecraft/config/MovingWorld
open Main.cfg
add below  S:block_densities <
in **this example**         "minecraft:lapis_block=32.00"
(You need to find out your blocks id-name and substitute it)

It should then look like this:

    S:block_densities <
        "DavincisVessels:floater=0.04"
        "DavincisVessels:balloon=0.02"
        "minecraft:lapis_block=32.00"
     >

I also did the same for     S:material_densities <
just to be sure:

    S:material_densities <
        "minecraft:air=0.0"
        "minecraft:wool=0.1"
        "minecraft:lapis_block=32.00"
     >

32 seems to be a good heavy value for me.
You can set this higher or lower of course.
