### ISSUE TITLE
How to update the mod

### ISSUE THREAD

**Issue by Radyfil** [darkevilmac/archimedes-ships-plus#335]
How to update the mod to version 1.14.4

**Comment by Luismi28** [comment]
x2

**Comment by emanuele246gi** [comment]
Wtf

**Comment by Luismi28** [comment]
I put x2 because I also want to know when it will update to version 1.14.4 xd

**Comment by darkevilmac** [comment]
Updates happen when I have time to make an update.

**Comment by Luismi28** [comment]
Ok
