### ISSUE TITLE
Do we have permission to use the name 'Davinci's'?

### ISSUE THREAD

**Issue by Rubydesic** [darkevilmac/archimedes-ships-plus#336]
I love control system that Davinci's Vessels has. It's fabulously intuitive, and we (the Valkyrien Skies team) are planning on making a fork of Davinci's to use Valkyrien Skies as the backend instead of MovingWorld. Would you mind if we called the extension mod 'Davinci's Vessels controls for Valkyrien Skies' or similar?

**Comment by darkevilmac** [comment]
Sorry but no.

I get enough off topic issues here as it is, having a mod that's completely unrelated to mine use the same name won't help with that.
