### ISSUE TITLE
Crash when mounting

### ISSUE THREAD

**Issue by chocolateBit0xD6** [darkevilmac/archimedes-ships-plus#35]
Hi, it crashes every time I mount the ship right after assembling, when I go back into the map after crashing I am mounted though and can get off and back on without a problem.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (SINGLE_movingworld-1.8-ALPHA-3.0.jar)
  Transformer (MULTI_EasyZoom[1.8][Forge].jar)
  NowWithRendering (MULTI_redstonepaste-mc1.8-1.7.1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10.07.15 16:00
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at darkevilmac.archimedes.client.render.TileEntityHelmRenderer.renderHelm(TileEntityHelmRenderer.java:48)
	at darkevilmac.archimedes.client.render.TileEntityHelmRenderer.func_180535_a(TileEntityHelmRenderer.java:39)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(SourceFile:114)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(SourceFile:102)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:655)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:333)
	at shadersmod.client.Shaders.beginRender(Shaders.java:2763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1192)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
	at noppes.mpm.client.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:32)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at darkevilmac.archimedes.client.render.TileEntityHelmRenderer.renderHelm(TileEntityHelmRenderer.java:48)
	at darkevilmac.archimedes.client.render.TileEntityHelmRenderer.func_180535_a(TileEntityHelmRenderer.java:39)

-- Block Entity Details --
Details:
	Name: archiHelm // darkevilmac.archimedes.common.tileentity.TileEntityHelm
	Block type: ID #200 (tile.archimedes.marker // darkevilmac.archimedes.common.object.block.BlockHelm)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-112,64,328), Chunk: (at 0,4,8 in -7,20; contains blocks -112,0,320 to -97,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(SourceFile:114)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(SourceFile:102)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:655)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:333)
	at shadersmod.client.Shaders.beginRender(Shaders.java:2763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1192)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Paripalini'/461, l='MpServer', x=-112,50, y=64,05, z=328,50]]
	Chunk stats: MultiplayerChunkCache: 607, 607
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -196,00,64,00,256,00 - World: (-196,64,256), Chunk: (at 12,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3424 game time, 3424 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 167 total; [EntityZombie['Zombie'/9216, l='MpServer', x=-119,50, y=12,00, z=275,50], EntityZombie['Zombie'/9217, l='MpServer', x=-117,72, y=11,03, z=274,28], EntityGib['unknown'/11267, l='MpServer', x=-50,50, y=40,50, z=352,50], EntityGib['unknown'/11268, l='MpServer', x=-50,80, y=40,28, z=352,68], EntityGib['unknown'/11269, l='MpServer', x=-50,20, y=40,28, z=352,32], EntityBat['Bat'/8213, l='MpServer', x=-51,75, y=54,66, z=386,78], EntityGib['unknown'/11310, l='MpServer', x=-46,50, y=62,50, z=254,50], EntityGib['unknown'/11311, l='MpServer', x=-46,15, y=62,28, z=254,47], EntityGib['unknown'/11312, l='MpServer', x=-46,85, y=62,28, z=254,53], EntityGib['unknown'/11316, l='MpServer', x=-46,50, y=39,50, z=262,50], EntityGib['unknown'/11317, l='MpServer', x=-46,28, y=39,28, z=262,22], EntityPlayerSP['Paripalini'/461, l='MpServer', x=-112,50, y=64,05, z=328,50], EntityGib['unknown'/11318, l='MpServer', x=-46,72, y=39,28, z=262,78], EntityZombie['Zombie'/10302, l='MpServer', x=-191,50, y=14,00, z=360,50], EntityZombie['Zombie'/10303, l='MpServer', x=-193,72, y=14,00, z=359,69], EntityCreeper['Creeper'/10305, l='MpServer', x=-193,03, y=14,00, z=358,53], EntityCreeper['Creeper'/10307, l='MpServer', x=-96,59, y=16,00, z=286,03], EntitySkeleton['Skeleton'/9283, l='MpServer', x=-48,50, y=39,00, z=378,50], EntityCreeper['Creeper'/10308, l='MpServer', x=-99,03, y=13,00, z=284,59], EntityGib['unknown'/586, l='MpServer', x=-101,56, y=41,50, z=312,81], EntityGib['unknown'/587, l='MpServer', x=-101,81, y=41,28, z=313,06], EntityGib['unknown'/13387, l='MpServer', x=-151,31, y=48,06, z=251,00], EntityGib['unknown'/588, l='MpServer', x=-101,32, y=41,28, z=312,57], EntityGib['unknown'/13388, l='MpServer', x=-151,49, y=47,84, z=251,30], EntityGib['unknown'/13389, l='MpServer', x=-151,14, y=47,84, z=250,70], EntityGib['unknown'/597, l='MpServer', x=-83,50, y=43,50, z=289,50], EntityGib['unknown'/598, l='MpServer', x=-83,62, y=43,28, z=289,17], EntityGib['unknown'/599, l='MpServer', x=-83,38, y=43,28, z=289,83], EntityGib['unknown'/601, l='MpServer', x=-93,56, y=43,50, z=311,84], EntityGib['unknown'/602, l='MpServer', x=-93,52, y=43,28, z=311,50], EntityGib['unknown'/603, l='MpServer', x=-93,61, y=43,28, z=312,19], EntitySpider['Spider'/9307, l='MpServer', x=-38,50, y=25,00, z=364,50], EntitySpider['Spider'/9308, l='MpServer', x=-40,50, y=25,00, z=364,50], EntityZombie['Zombie'/9321, l='MpServer', x=-46,50, y=61,00, z=254,50], EntityZombie['Zombie'/5237, l='MpServer', x=-119,50, y=12,00, z=280,50], EntityZombie['Zombie'/9336, l='MpServer', x=-55,50, y=26,00, z=368,50], EntityZombie['Zombie'/9337, l='MpServer', x=-55,50, y=26,00, z=373,50], EntitySpider['Spider'/9338, l='MpServer', x=-49,50, y=26,00, z=367,50], EntityWitch['Witch'/8835, l='MpServer', x=-50,50, y=38,00, z=268,50], EntityZombie['Zombie'/8836, l='MpServer', x=-46,50, y=38,00, z=262,50], EntityBat['Bat'/13959, l='MpServer', x=-54,53, y=46,28, z=346,88], EntityGib['unknown'/653, l='MpServer', x=-133,50, y=49,50, z=261,50], EntityGib['unknown'/5261, l='MpServer', x=-119,50, y=13,50, z=280,50], EntityGib['unknown'/654, l='MpServer', x=-133,30, y=49,28, z=261,79], EntityGib['unknown'/5262, l='MpServer', x=-119,72, y=13,28, z=280,77], EntityGib['unknown'/11918, l='MpServer', x=-191,50, y=15,50, z=360,50], EntityGib['unknown'/655, l='MpServer', x=-133,70, y=49,28, z=261,21], EntityGib['unknown'/5263, l='MpServer', x=-119,28, y=13,28, z=280,23], EntityGib['unknown'/11919, l='MpServer', x=-191,80, y=15,28, z=360,31], EntityGib['unknown'/11920, l='MpServer', x=-191,20, y=15,28, z=360,69], EntityGib['unknown'/664, l='MpServer', x=-80,28, y=12,50, z=258,66], EntityGib['unknown'/665, l='MpServer', x=-80,59, y=12,28, z=258,49], EntityGib['unknown'/666, l='MpServer', x=-79,98, y=12,28, z=258,83], EntityGib['unknown'/6827, l='MpServer', x=-166,44, y=49,50, z=254,06], EntityGib['unknown'/6828, l='MpServer', x=-166,20, y=49,28, z=253,80], EntityGib['unknown'/6829, l='MpServer', x=-166,67, y=49,28, z=254,32], EntityGib['unknown'/9392, l='MpServer', x=-119,50, y=13,50, z=275,50], EntityGib['unknown'/9393, l='MpServer', x=-119,70, y=13,28, z=275,79], EntityGib['unknown'/9394, l='MpServer', x=-119,30, y=13,28, z=275,21], EntityGib['unknown'/691, l='MpServer', x=-79,88, y=12,50, z=255,88], EntityGib['unknown'/692, l='MpServer', x=-79,54, y=12,28, z=255,97], EntityGib['unknown'/9396, l='MpServer', x=-117,72, y=12,53, z=274,28], EntityGib['unknown'/693, l='MpServer', x=-80,21, y=12,28, z=255,78], EntityGib['unknown'/9397, l='MpServer', x=-118,04, y=12,31, z=274,43], EntityGib['unknown'/9398, l='MpServer', x=-117,40, y=12,31, z=274,13], EntityGib['unknown'/695, l='MpServer', x=-71,97, y=16,50, z=261,47], EntityGib['unknown'/696, l='MpServer', x=-72,31, y=16,28, z=261,54], EntityGib['unknown'/697, l='MpServer', x=-71,63, y=16,28, z=261,40], EntityTrail['unknown'/699, l='MpServer', x=-112,50, y=64,05, z=328,50], EntityShip['entity.ArchimedesShipsPlus.shipmod.name'/14027, l='MpServer', x=-112,00, y=62,90, z=328,50], EntityHorse['Horse'/225, l='MpServer', x=-180,28, y=64,00, z=287,06], EntitySheep['Sheep'/226, l='MpServer', x=-176,31, y=64,00, z=282,13], EntitySheep['Sheep'/227, l='MpServer', x=-176,97, y=64,00, z=276,00], EntitySheep['Sheep'/228, l='MpServer', x=-184,50, y=63,00, z=288,53], EntityHorse['Horse'/229, l='MpServer', x=-181,47, y=64,00, z=288,91], EntitySkeleton['Skeleton'/234, l='MpServer', x=-166,44, y=48,00, z=254,06], EntityHorse['Horse'/235, l='MpServer', x=-171,22, y=64,00, z=284,47], EntitySheep['Sheep'/236, l='MpServer', x=-173,50, y=65,00, z=289,81], EntityZombie['Zombie'/259, l='MpServer', x=-133,50, y=48,00, z=261,50], EntityCreeper['Creeper'/260, l='MpServer', x=-132,44, y=54,00, z=328,03], EntityCreeper['Creeper'/261, l='MpServer', x=-127,41, y=51,00, z=325,97], EntityBat['Bat'/3852, l='MpServer', x=-62,27, y=40,96, z=282,45], EntityItem['item.item.seeds'/270, l='MpServer', x=-118,88, y=62,00, z=270,72], EntityBat['Bat'/3854, l='MpServer', x=-79,45, y=38,03, z=281,33], EntityItem['item.item.seeds'/272, l='MpServer', x=-125,53, y=64,00, z=318,41], EntitySquid['Squid'/273, l='MpServer', x=-119,87, y=58,06, z=324,80], EntitySquid['Squid'/274, l='MpServer', x=-106,79, y=61,01, z=311,30], EntitySquid['Squid'/275, l='MpServer', x=-102,43, y=60,17, z=298,47], EntityPig['Pig'/276, l='MpServer', x=-129,16, y=97,00, z=342,47], EntityPig['Pig'/277, l='MpServer', x=-117,31, y=82,00, z=336,50], EntityPig['Pig'/278, l='MpServer', x=-123,50, y=93,00, z=400,50], EntityPig['Pig'/279, l='MpServer', x=-124,50, y=87,00, z=401,50], EntityPig['Pig'/280, l='MpServer', x=-124,50, y=85,00, z=402,50], EntityPig['Pig'/281, l='MpServer', x=-121,50, y=94,00, z=400,50], EntitySheep['Sheep'/289, l='MpServer', x=-99,56, y=72,00, z=266,78], EntitySheep['Sheep'/290, l='MpServer', x=-91,13, y=73,00, z=261,91], EntitySheep['Sheep'/291, l='MpServer', x=-100,94, y=70,00, z=265,34], EntitySheep['Sheep'/292, l='MpServer', x=-109,69, y=65,00, z=256,53], EntitySquid['Squid'/293, l='MpServer', x=-102,92, y=62,24, z=297,95], EntityItem['item.item.seeds'/294, l='MpServer', x=-100,59, y=63,00, z=289,84], EntitySkeleton['Skeleton'/296, l='MpServer', x=-101,56, y=40,00, z=312,81], EntitySquid['Squid'/297, l='MpServer', x=-98,63, y=62,38, z=294,09], EntityPig['Pig'/298, l='MpServer', x=-104,03, y=85,00, z=332,22], EntityPig['Pig'/299, l='MpServer', x=-101,09, y=103,00, z=346,25], EntityPig['Pig'/300, l='MpServer', x=-100,81, y=110,00, z=377,53], EntityPig['Pig'/301, l='MpServer', x=-103,50, y=111,00, z=379,50], EntityPig['Pig'/302, l='MpServer', x=-105,06, y=109,00, z=376,53], EntityPig['Pig'/303, l='MpServer', x=-103,44, y=110,00, z=377,59], EntityGib['unknown'/10551, l='MpServer', x=-59,50, y=40,50, z=277,50], EntityGib['unknown'/10552, l='MpServer', x=-59,85, y=40,28, z=277,53], EntityGib['unknown'/10553, l='MpServer', x=-59,15, y=40,28, z=277,47], EntityZombie['Zombie'/11578, l='MpServer', x=-151,31, y=46,56, z=251,00], EntityGib['unknown'/10555, l='MpServer', x=-58,50, y=40,50, z=276,50], EntityGib['unknown'/10556, l='MpServer', x=-58,15, y=40,28, z=276,50], EntityGib['unknown'/10557, l='MpServer', x=-58,85, y=40,28, z=276,50], EntityGib['unknown'/10559, l='MpServer', x=-58,50, y=40,50, z=278,50], EntityGib['unknown'/10560, l='MpServer', x=-58,53, y=40,28, z=278,85], EntityGib['unknown'/10561, l='MpServer', x=-58,47, y=40,28, z=278,15], EntityCow['Cow'/324, l='MpServer', x=-90,16, y=73,00, z=263,13], EntityCow['Cow'/325, l='MpServer', x=-82,25, y=63,00, z=280,78], EntityCow['Cow'/326, l='MpServer', x=-89,75, y=67,00, z=274,53], EntityCow['Cow'/327, l='MpServer', x=-78,56, y=72,00, z=273,34], EntitySkeleton['Skeleton'/329, l='MpServer', x=-83,50, y=42,00, z=289,50], EntitySkeleton['Skeleton'/330, l='MpServer', x=-93,56, y=42,00, z=311,84], EntitySkeleton['Skeleton'/9549, l='MpServer', x=-59,50, y=39,00, z=277,50], EntityZombie['Zombie'/9551, l='MpServer', x=-58,50, y=39,00, z=276,50], EntityZombie['Zombie'/9552, l='MpServer', x=-58,50, y=39,00, z=278,50], EntityZombie['Zombie'/9553, l='MpServer', x=-50,50, y=39,00, z=352,50], EntityZombie['Zombie'/345, l='MpServer', x=-79,88, y=11,00, z=255,88], EntityZombie['Zombie'/347, l='MpServer', x=-71,97, y=15,00, z=261,47], EntityCreeper['Creeper'/349, l='MpServer', x=-64,50, y=52,00, z=255,50], EntityZombie['Zombie'/350, l='MpServer', x=-80,28, y=11,00, z=258,66], Bear['Grizzly Bear'/351, l='MpServer', x=-64,50, y=76,00, z=287,50], Bear['Grizzly Bear'/352, l='MpServer', x=-66,50, y=74,00, z=287,50], Bear['Grizzly Bear'/353, l='MpServer', x=-68,50, y=70,00, z=287,50], EntityBat['Bat'/380, l='MpServer', x=-46,89, y=38,04, z=262,18], Bear['Grizzly Bear'/381, l='MpServer', x=-61,50, y=87,00, z=288,50], EntitySkeleton['Skeleton'/382, l='MpServer', x=-53,50, y=28,00, z=348,84], EntityBat['Bat'/385, l='MpServer', x=-46,41, y=27,10, z=394,44], EntityCreeper['Creeper'/12184, l='MpServer', x=-70,50, y=74,00, z=362,50], EntitySheep['Sheep'/415, l='MpServer', x=-39,75, y=115,00, z=358,09], EntitySheep['Sheep'/416, l='MpServer', x=-46,97, y=122,00, z=370,09], EntitySquid['Squid'/3492, l='MpServer', x=-75,56, y=59,06, z=288,59], EntitySquid['Squid'/3493, l='MpServer', x=-83,78, y=62,44, z=287,47], EntitySquid['Squid'/3495, l='MpServer', x=-79,53, y=59,41, z=290,47], EntityGib['unknown'/12762, l='MpServer', x=-193,72, y=15,50, z=359,69], EntityGib['unknown'/12763, l='MpServer', x=-193,63, y=15,28, z=360,03], EntityGib['unknown'/12764, l='MpServer', x=-193,80, y=15,28, z=359,35], EntityBat['Bat'/9184, l='MpServer', x=-89,97, y=17,19, z=309,94], EntityBat['Bat'/9185, l='MpServer', x=-80,44, y=12,00, z=311,75], EntityGib['unknown'/10724, l='MpServer', x=-55,50, y=27,50, z=368,50], EntitySkeleton['Skeleton'/8165, l='MpServer', x=-84,50, y=43,00, z=294,50], EntityGib['unknown'/10725, l='MpServer', x=-55,34, y=27,28, z=368,19], EntityGib['unknown'/10726, l='MpServer', x=-55,66, y=27,28, z=368,81], EntityGib['unknown'/10728, l='MpServer', x=-55,50, y=27,50, z=373,50], EntityGib['unknown'/10729, l='MpServer', x=-55,15, y=27,28, z=373,50], EntityGib['unknown'/10730, l='MpServer', x=-55,85, y=27,28, z=373,50], EntityGib['unknown'/10732, l='MpServer', x=-53,50, y=29,50, z=348,84], EntityGib['unknown'/10733, l='MpServer', x=-53,78, y=29,28, z=348,63], EntityGib['unknown'/10734, l='MpServer', x=-53,22, y=29,28, z=349,06], EntityGib['unknown'/8177, l='MpServer', x=-84,50, y=44,50, z=294,50], EntityGib['unknown'/8178, l='MpServer', x=-84,16, y=44,28, z=294,44], EntityGib['unknown'/8179, l='MpServer', x=-84,84, y=44,28, z=294,56], EntityGib['unknown'/11258, l='MpServer', x=-48,50, y=40,50, z=378,50], EntityGib['unknown'/11259, l='MpServer', x=-48,15, y=40,28, z=378,50], EntityGib['unknown'/11260, l='MpServer', x=-48,85, y=40,28, z=378,50], EntityBat['Bat'/11774, l='MpServer', x=-118,21, y=25,97, z=244,20]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 186024280 bytes (177 MB) / 1117708288 bytes (1065 MB) up to 6415646720 bytes (6118 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms512M -Xmn256M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1486 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1486.jar) 
	UCHIJAAAA	Forge{11.14.3.1486} [Minecraft Forge] (forge-1.8-11.14.3.1486.jar) 
	UCHIJAAAA	EAZY-ZOOM{0.0.0} [EAZY ZOOM for Forge] (minecraft.jar) 
	UCHIJAAAA	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	ChickenShed{1.1.4} [Chicken Shed] (MULTI_[1.8] ChickenShed (v1.2.0).jar) 
	UCHIJAAAA	bspkrsCore{7.01} [bspkrsCore] (MULTI_[1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAAAA	StatusEffectHUD{1.8} [StatusEffectHUD] (MULTI_[1.8]StatusEffectHUD-client-1.27.jar) 
	UCHIJAAAA	Treecapitator{1.8} [Treecapitator] (MULTI_[1.8]Treecapitator-universal-2.0.5.jar) 
	UCHIJAAAA	BaMsGRAVE{@VERSION@} [BaM's Grave] (MULTI_BaMsGRAVE-1.8-1.4.4-SNAPSHOT-1.jar) 
	UCHIJAAAA	BetterHorseHud{1.0} [Better Horse Hud] (MULTI_BetterHorseHud-1.8.jar) 
	UCHIJAAAA	EAZY-ZOOM_{0.0.0} [EAZY-ZOOM_INGAME_KEYBINDER] (MULTI_EasyZoom[1.8][Forge].jar) 
	UCHIJAAAA	eplus{3.1.0a1} [Enchanting Plus] (MULTI_EnchantingPlus-1.8-3.1.0a1.jar) 
	UCHIJAAAA	iChunUtil{5.3.0} [iChunUtil] (MULTI_iChunUtil-5.3.0.jar) 
	UCHIJAAAA	igneousadditions{1.1} [Igneous Additions] (MULTI_IgneousAdditions-1.1.jar) 
	UCHIJAAAA	latticemod{1.1} [Lattice Mod] (MULTI_latticemod-mc1.8-1.1.jar) 
	UCHIJAAAA	MobAmputation{5.0.0} [MobAmputation] (MULTI_MobAmputation-5.0.0.jar) 
	UCHIJAAAA	moreplayermodels{1.8.0_beta} [MorePlayerModels] (MULTI_MorePlayerModels_1.8.0_beta.jar) 
	UCHIJAAAA	redstonepaste{1.7.1} [Redstone Paste] (MULTI_redstonepaste-mc1.8-1.7.1.jar) 
	UCHIJAAAA	zyinhud{1.4.2} [Zyin's HUD] (MULTI_ZyinsHUD-(1.8)-v.1.4.2.jar) 
	UCHIJAAAA	MovingWorld{1.8-ALPHA-3.0} [Moving World] (SINGLE_movingworld-1.8-ALPHA-3.0.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.8-ALPHA-3.0} [Archimedes' Ships Plus] (SINGLE_archimedesshipsplus-1.8-ALPHA-3.0.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (SINGLE_Backpacks-Mod-1.8.jar) 
	UCHIJAAAA	bc{1.0} [Ollij93's BowCraft] (SINGLE_BowCraft-1.1.jar) 
	UCHIJAAAA	Chameleon{1.8-0.1.0} [Chameleon] (SINGLE_Chameleon-1.8-0.1.0.jar) 
	UCHIJAAAA	F2L{1.8} [Flesh2Leather] (SINGLE_Flesh2Leather [1.8].jar) 
	UCHIJAAAA	GakaisFlightTable{1.1.1} [Gakais Flight Table] (SINGLE_GakaisFlightTable-1.8-1.1.1.jar) 
	UCHIJAAAA	fishing{1.4} [Fishing Net Mod] (SINGLE_GiacomosFishingNet1.8-1.4.jar) 
	UCHIJAAAA	magicyarn{1.1.6} [Magic Yarn] (SINGLE_MagicYarn-1.8.jar) 
	UCHIJAAAA	corerm{1.2} [RikMuld's Core] (SINGLE_RikMuldsCore_1.2.jar) 
	UCHIJAAAA	Scenter{1.8-3.3.0} [Scenter] (SINGLE_scenter-1.8-3.3.0.jar) 
	UCHIJAAAA	camping{2.2} [The Camping Mod 2] (SINGLE_TheCampingMod_2.2b.jar) 
	UCHIJAAAA	throwabletorchmod{1.0.0} [ThrowableTorchMod] (SINGLE_throwabletorchmod-1.8-1.0.jar) 
	UCHIJAAAA	teleporter{1.4.2} [Vanilla-Inspired Teleporters] (SINGLE_VanillaTeleporter-1.8-1.4.2.jar) 
	UCHIJAAAA	YAFM{1.0.4} [Yet Another Food Mod] (SINGLE_yafm-1.0.4.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (SINGLE_movingworld-1.8-ALPHA-3.0.jar)
  
Transformer (MULTI_EasyZoom[1.8][Forge].jar)
  easyzoom.Transformer
NowWithRendering (MULTI_redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 780/PCIe/SSE2'
	Launched Version: 1.8-Forge11.14.3.1486
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 780/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [John Smith Legacy 1.8]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by darkevilmac** [comment]
Seems to be an issue with the new helm renderer, I'll take a look now.
