### ISSUE TITLE
Server crashes cannot start the mod

### ISSUE THREAD

**Issue by okuue** [darkevilmac/archimedes-ships-plus#361]
I use Aternos Magma on 1.12.2 and everytime i try starting the server, at the end it crashes.

here's the log :

[23:19:05] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
1491 | net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moving World (movingworld)
1492 |  
1493 | Caused by: java.lang.NullPointerException
1494 | at com.elytradev.movingworld.common.config.priority.AssemblePriorityConfig.discoverPoweredBlocks(AssemblePriorityConfig.java:168) ~[movingworld-1.12-6.342-full.jar:?]
1495 | at com.elytradev.movingworld.common.config.priority.AssemblePriorityConfig.loadAndSaveInit(AssemblePriorityConfig.java:87) ~[movingworld-1.12-6.342-full.jar:?]
1496 | at com.elytradev.movingworld.MovingWorldMod.init(MovingWorldMod.java:46) ~[movingworld-1.12-6.342-full.jar:?]
1497 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
1498 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
1499 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
1500 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
1501 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[server.jar:bb50f45]
1502 | at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
1503 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
1504 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
1505 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1506 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1507 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1508 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1509 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1510 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1511 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1512 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[server.jar:bb50f45]
1513 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[server.jar:bb50f45]
1514 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
1515 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
1516 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
1517 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
1518 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1519 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1520 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1521 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1522 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1523 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1524 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1525 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:bb50f45]
1526 | at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724) ~[Loader.class:bb50f45]
1527 | at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112) ~[FMLServerHandler.class:bb50f45]
1528 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340) ~[FMLCommonHandler.class:bb50f45]
1529 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:269) ~[nz.class:?]
1530 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688) [MinecraftServer.class:?]
1531 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
1532 | [23:19:05] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2021-01-14_23.19.05-server.txt

I'm kinda new to mods and stuff but is there a way to fix this?

**Comment by okuue** [comment]
I just want to play the mod with my friends on my aternos magma server is there a way to fix it plspslpsl

**Comment by dadcuy** [comment]
Aternos mostly does all not support mods so i suggest you should use falixnodes as a host its free
but i am giving you a warning that it may be much harder than aternos but you should give it a try

**Comment by okuue** [comment]
> Aternos mostly does all not support mods so i suggest you should use falixnodes as a host its free
> but i am giving you a warning that it may be much harder than aternos but you should give it a try

Nvm i sorted it out by having a seperate server and downloading DV first on it, then moving all the world data and mods over, and it worked miraculously!
