### ISSUE TITLE
Crash when opening ship's helm while wearing exosuit chestpiece from Flaxbeard's steam mod with steam stored in it.

### ISSUE THREAD

**Issue by davetheknave** [darkevilmac/archimedes-ships-plus#38]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 7/28/15 7:52 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1022)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1022)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['<PROFILE NAME>'/206, l='MpServer', x=213.64, y=142.62, z=-1112.61]]
Chunk stats: MultiplayerChunkCache: 289, 298
Level seed: 0
Level generator: ID 04 - ATG, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (246,64,-1168), Chunk: (at 6,4,0 in 15,-73; contains blocks 240,0,-1168 to 255,255,-1153), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
Level time: 5084799 game time, 173705 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 39 total; [EntitySkeleton['Skeleton'/51584, l='MpServer', x=254.47, y=34.17, z=-1060.19], EntityZombie['Zombie'/129, l='MpServer', x=242.70, y=29.00, z=-1068.70], EntityMobEnderman['Enderman'/257, l='MpServer', x=184.50, y=212.00, z=-1142.50], EntityBat['Bat'/51588, l='MpServer', x=274.44, y=41.06, z=-1059.13], EntityZombie['Zombie'/138, l='MpServer', x=264.47, y=18.00, z=-1054.75], EntityBat['Bat'/51594, l='MpServer', x=275.88, y=42.00, z=-1061.00], EntityZombie['Zombie'/139, l='MpServer', x=258.78, y=27.00, z=-1035.63], EntityChicken['Chicken'/149, l='MpServer', x=287.78, y=64.00, z=-1168.22], EntityZombie['Zombie'/150, l='MpServer', x=283.84, y=11.00, z=-1164.50], EntityChicken['Chicken'/151, l='MpServer', x=287.81, y=64.00, z=-1166.25], EntityChicken['Chicken'/152, l='MpServer', x=287.78, y=64.00, z=-1166.84], EntityChicken['Chicken'/153, l='MpServer', x=287.78, y=64.00, z=-1167.47], EntityChicken['Chicken'/154, l='MpServer', x=287.78, y=64.00, z=-1165.75], EntityBat['Bat'/9882, l='MpServer', x=155.94, y=39.00, z=-1113.84], EntityChicken['Chicken'/163, l='MpServer', x=291.22, y=64.00, z=-1168.22], EntityChicken['Chicken'/164, l='MpServer', x=290.16, y=64.00, z=-1168.13], EntityChicken['Chicken'/165, l='MpServer', x=288.34, y=64.00, z=-1168.22], EntityChicken['Chicken'/166, l='MpServer', x=288.69, y=64.00, z=-1164.78], EntityChicken['Chicken'/167, l='MpServer', x=290.94, y=64.00, z=-1167.22], EntityChicken['Chicken'/168, l='MpServer', x=287.97, y=64.00, z=-1164.97], EntityChicken['Chicken'/169, l='MpServer', x=291.22, y=64.00, z=-1166.59], EntityChicken['Chicken'/170, l='MpServer', x=288.72, y=64.00, z=-1165.47], EntityChicken['Chicken'/171, l='MpServer', x=288.34, y=64.00, z=-1166.13], EntityChicken['Chicken'/172, l='MpServer', x=290.34, y=64.00, z=-1165.88], EntitySquid['Squid'/14124, l='MpServer', x=169.53, y=59.06, z=-1065.41], EntityCreeper['Creeper'/28862, l='MpServer', x=212.50, y=43.00, z=-1179.50], EntityZombie['Zombie'/69, l='MpServer', x=141.91, y=28.00, z=-1075.41], EntityZombie['Zombie'/77, l='MpServer', x=154.66, y=11.94, z=-1127.69], EntityZombie['Zombie'/14285, l='MpServer', x=257.09, y=30.00, z=-1080.56], EntityClientPlayerMP['<PROFILE NAME>'/206, l='MpServer', x=213.64, y=142.62, z=-1112.61], EntityCartChest['entity.MinecartChest.name'/86, l='MpServer', x=172.50, y=12.50, z=-1205.88], EntityCartChest['entity.MinecartChest.name'/87, l='MpServer', x=172.50, y=12.50, z=-1207.50], EntityZombie['Zombie'/14427, l='MpServer', x=159.50, y=44.00, z=-1078.50], EntitySpark['Spark'/97, l='MpServer', x=186.50, y=139.50, z=-1128.50], EntityZombie['Zombie'/28898, l='MpServer', x=210.50, y=43.00, z=-1181.50], EntitySpark['Spark'/107, l='MpServer', x=192.50, y=140.31, z=-1124.50], EntitySpark['Spark'/108, l='MpServer', x=192.50, y=140.31, z=-1130.50], EntitySpider['Spider'/50163, l='MpServer', x=254.47, y=34.00, z=-1060.19], EntityPig['Pig'/117, l='MpServer', x=218.81, y=69.00, z=-1184.28]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_45, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 562601472 bytes (536 MB) / 1328545792 bytes (1267 MB) up to 1908932608 bytes (1820 MB)
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m -XX:PermSize=256m
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 51485, allocated: 0, tallocated: 16
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_B7 58 mods loaded, 58 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar)
UCHIJAAAA Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar)
UCHIJAAAA Aroma1997Core{1.0.2.14} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.14.jar)
UCHIJAAAA CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar)
UCHIJAAAA OldModelLoader{1.0} [OldModelLoader] (minecraft.jar)
UCHIJAAAA NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar)
UCHIJAAAA <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
UCHIJAAAA DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar)
UCHIJAAAA AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar)
UCHIJAAAA MovingWorld{1.7.10-1.7.12B} [Moving World] (movingworld-1.7.10-1.7.12B.jar)
UCHIJAAAA ArchimedesShipsPlus{1.7.10-1.7.12} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.7.12.jar)
UCHIJAAAA Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.14.jar)
UCHIJAAAA AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar)
UCHIJAAAA ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar)
UCHIJAAAA BetterFoliage{1.0.13} [Better Foliage] (BetterFoliage-mc1.7-1.0.13.jar)
UCHIJAAAA BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar)
UCHIJAAAA bigtrees{1.7.2b} [The BigTrees Mod] (BigTrees-172b-forge1060.jar)
UCHIJAAAA Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
UCHIJAAAA Botania{r1.7-207} [Botania] (Botania r1.7-207.jar)
UCHIJAAAA dimdoors{2.2.5-test} [Dimensional Doors] (DimensionalDoors-2.2.5-test8.jar)
UCHIJAAAA Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar)
UCHIJAAAA TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar)
UCHIJAAAA DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V7f.jar)
UCHIJAAAA enchvil{1.0} [Enchvil Mod] (enchvil-1.7.2-V1.1.jar)
UCHIJAAAA ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar)
UCHIJAAAA factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.95(2).jar)
UCHIJAAAA factorization.dimensionalSlice{0.8.95} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.95(2).jar)
UCHIJAAAA factorization{0.8.95} [Factorization] (Factorization-1.7.10-0.8.95(2).jar)
UCHIJAAAA factorization.misc{0.8.95} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.95(2).jar)
UCHIJAAAA FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
UCHIJAAAA Steamcraft{0.28.7} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.7.jar)
UCHIJAAAA GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar)
UCHIJAAAA GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar)
UCHIJAAAA GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar)
UCHIJAAAA GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar)
UCHIJAAAA HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion MC-1.7.10 v1.8.2.jar)
UCHIJAAAA HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar)
UCHIJAAAA inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar)
UCHIJAAAA IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar)
UCHIJAAAA LLadders{0.5.0} [Luppii's Ladders] (Ladders-0.5.0-MC1.7.10.jar)
UCHIJAAAA lmmx{1.0} [lmmx] (littleMaidMobX-1.7.x_0.0.8pre3.jar)
UCHIJAAAA MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.x_0.0.8pre3.jar)
UCHIJAAAA zabuton{1.0} [zabuton] (littleMaidMobX-1.7.x_0.0.8pre3.jar)
UCHIJAAAA MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar)
UCHIJAAAA MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar)
UCHIJAAAA mod_Modchu_ModchuLib{179-10} [mod_Modchu_ModchuLib] (ModchuLib_1_7_10-v10f.zip)
UCHIJAAAA neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar)
UCHIJAAAA Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar)
UCHIJAAAA RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar)
UCHIJAAAA Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar)
UCHIJAAAA StorageDrawers{1.7.10-1.5.4} [Storage Drawers] (StorageDrawers-1.7.10-1.5.4.jar)
UCHIJAAAA TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar)
UCHIJAAAA UndergroundBiomes{0.6h} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.6h13.jar)
UCHIJAAAA worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar)
UCHIJAAAA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJAAAA HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar)
UCHIJAAAA IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar)
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
TConstruct Environment: Environment healthy.
Launched Version: 1.7.10
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Pixel Reality 1.8.2, Isabella II FTB, Dave Tweaks, skin - alucard]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
[07:52:05] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\david\Downloads\MultiMC\instances\1.7.10-M David\minecraft\crash-reports\crash-2015-07-28_07.52.03-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Minecraft exited with exitcode -1.

**Comment by darkevilmac** [comment]
Please update your issue to match the new guidelines. https://github.com/darkevilmac/archimedes-ships-plus/issues/39
