### ISSUE TITLE
READ BEFORE MAKING AN ISSUE

### ISSUE THREAD

**Issue by darkevilmac** [darkevilmac/archimedes-ships-plus#39]
I'm making this because the issue reports have gotten a bit ridiculous at this point. 

1. Do NOT post your error in the issue directly, please use http://hastebin.com/ or http://pastebin.com/
2. Do NOT post the entire description of your error in the title, the title is just a very short explanation.
3. DO post information about the crash you were able to discover in the actual issue text.
4. DO see if the issue occurs with just AS+ and MovingWorld installed, so I know if it's an incompatibility issue.

Here's a basic do and don't.

DON'T
=================================================================================
Title: Issue with Mod X that causes crash when I do x in scenario y but only sometimes

CRASH LOG

DO
=================================================================================
Title: Mod incompatibility with Mod X

I'm experiencing a crash when I do x in scenario y, it's not consistent though as it only happens sometimes.

Here's my crash log: http://hastebin.com/fecovewite.vbs

**Comment by darkevilmac** [comment]
Just a quick addendum, if you have no crash log ALWAYS include FML's latest log.

**Comment by JCMais** [comment]
You probably should add this as a CONTRIBUTING file, since Github automatically shows a link to it on issue creation: https://github.com/blog/1184-contributing-guidelines

**Comment by darkevilmac** [comment]
I was unaware of that, will do :)
