### ISSUE TITLE
Incompatibility With ArchitectureCraft

### ISSUE THREAD

**Issue by jadenPete** [darkevilmac/archimedes-ships-plus#42]
Whenever I assemble / dissasemble my planes, boats, subs, etc near slopes, pillars, etc from ArchitectureCraft, they turn into the default shape (a wooden slope). Here's my latest.log:
http://pastebin.com/iJJQyYev
![2015-08-03_19 06 48](https://cloud.githubusercontent.com/assets/13180372/9051810/db5959f0-3a14-11e5-8926-6eb5cf746b52.png)
![2015-08-03_19 08 24](https://cloud.githubusercontent.com/assets/13180372/9051813/e0a5b084-3a14-11e5-90fc-8fa07cbf55ab.png)
![2015-08-03_19 09 07](https://cloud.githubusercontent.com/assets/13180372/9051815/e54eb072-3a14-11e5-8d92-80345dd75596.png)

**Comment by darkevilmac** [comment]
So does this happen on assembly, or on disassembly? Also,  could I have a link to ArchitectureCraft?

**Comment by jadenPete** [comment]
I've experimented with this, and when I dissasemble, it happens. So I assembled and got on it, moved it to another location, got out of it, fixed the slopes, and drove it back there and dissasembled it. It happened again. So it looks like it happens on both. Oh and here's the link to ArchitectureCraft:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2489461-architecturecraft-1-0-0-for-minecraft-1-8-0

**Comment by jadenPete** [comment]
If I reload the world it goes back to normal. This also happen's with WorldEdit  and other mods. Don't think it's a problem with ur mod. Thanks 4 helping though :)

**Comment by darkevilmac** [comment]
Hmm, so if you reload the world it changes back, most likely a desync issue
then.

**Comment by jadenPete** [comment]
You got it. I think it's a problem with ArchitectureCraft. I would tell him, but he doesn't seem to very active. Can you help me?

**Comment by darkevilmac** [comment]
Closing as it seems to be an issue with that mod more than AS+. Not something I can fix without making a special exception in the code and if I did that for every mod that didn't work I would have A LOT of exceptions to make. :stuck_out_tongue:
