### ISSUE TITLE
server doesn't start

### ISSUE THREAD

**Issue by Zeph0s** [darkevilmac/archimedes-ships-plus#44]
Tried updating from 1.7.10 with the original AS mod plus one other mod (TreeCapitator) to 1.8 with AS+ and the other mod. It looks like FML caught an exception related to mapping the new blocks.

http://hastebin.com/epafikupok.coffee

**Comment by darkevilmac** [comment]
1.7 -> 1.8 maps will not transition. And you can only change blocks to AS+ when you have both mods installed.

**Comment by Zeph0s** [comment]
Thanks, FYI as a workaround I just updated 1.7 -> 1.8 with no mods and then restarted the server after inserting the mods.
