### ISSUE TITLE
Suggestions for Anchors, Redstone , Winches And Magnetic Hooks

### ISSUE THREAD

**Issue by lifeNerd** [darkevilmac/archimedes-ships-plus#45]
1. Anchors:
Ship to Ship - linking --> to align an dinghy-Airship under (or behind or beside) the mothership

2. Redstone:
--make Trigger-Blocks with a GUI to set a Name/Channel and a Subpage in the Ship-Inventory to switch the Redstone-State of all Trigger-Blocks that are connected with the ship
-- by switch a state in the ship-inventory, all Trigger with the same Name/Channel switch her state
-- make Pistons, Dispenser and other vanilla Blocks usable in a assembled ship

3. Winches:
-- make Winches to lowering a dinghy or unload Cargo without landing or diassembling
-- may be require an engine as a driving
-- Winds should - exactly as Trigger-Blocks from 2. - assigned to a Name/Channel and controlled by Ship-Inventory

4.  Magnetic Hooks 
-- a Block to lowering and release a dinghy or unload Cargo
-- Hooks should - exactly as Trigger-Blocks from 2. - assigned to a Name/Channel and controlled by Ship-Inventory

**Comment by darkevilmac** [comment]
Not added but as this is for issues I think I'll close it for the time being.
