### ISSUE TITLE
Server config fails to take precedence over client config

### ISSUE THREAD

**Issue by magneticflux-** [darkevilmac/archimedes-ships-plus#46]
Expected Behavior:
The server's config takes precedence and the client obeys whatever craft settings the server owner has set.

Actual Behavior:
The client disagrees on the craft's position, causing rubberbanding. Crafts are impossible to use if the configuration files differ.

Testing:
To test, just create a server, change acceleration and/or balloon percent only on the server config.

**Comment by darkevilmac** [comment]
Can be fixed in code by having a packet sent on player connect.

**Comment by DPxKnightxZero** [comment]
Is this bug fixed?

**Comment by magneticflux-** [comment]
@DPxKnightxZero The issue isn't closed, so I would assume no.

**Comment by darkevilmac** [comment]
I've been crazy busy with life so unfortunately I haven't had a huge amount
of time to work on developing the mod. Hopefully, I'll have some more time
to fix bugs in the near future.

**Comment by DPxKnightxZero** [comment]
Alright well I will wait for it to get fixed.

**Comment by darkevilmac** [comment]
Currently being worked on if you look at some of the most recent configs. Yet to be tested but it should work fairly well.

**Comment by DPxKnightxZero** [comment]
Where do I get the test release?

**Comment by darkevilmac** [comment]
Gson stuffs was finished a while back, forgot to close the issue.

Try the 1.8.9 build it should work on that. (Can't remember if I backported it yet.)
