### ISSUE TITLE
Rotating with ExtraUtils and ThermalExp. Pipes

### ISSUE THREAD

**Issue by PumaBlack** [darkevilmac/archimedes-ships-plus#48]
At first Congrats for this Mod - BIG THX!

The Issues:
MC 1.7.10
Forge10.13.4.1492

ExtraUtilitis (extrautilities-1.2.10.jar)
The Itemnodes do not rotate. The Pipes does rotate.

Thermal Expansion (ThermalExpansion-[1.7.10]4.0.3B1-218.jar)
The Pipes have rotating problems, they rotate, but they create random conections and crosssections to the air and wont work.

ProjectRed-1.7.10-4.7.0pre8.92
The red redstone wires disapear after mounting the ship and they wont come back after dismount.

**Comment by PumaBlack** [comment]
sorry i forgot the Mod: archimedesshipsplus-1.7.10-1.7.12.jar

**Comment by darkevilmac** [comment]
You need to configure rotation for blocks from other mods in the mrot folder under configs.

ProjectRed on the other hand, I'm not entirely sure about. It's more likely being popped off when the ship sets the blocks to air. Not a whole lot I can do about that unfortunately.

**Comment by PumaBlack** [comment]
There is no mrot folder. Please can you explain it a bit more. Thank you.

**Comment by darkevilmac** [comment]
configs/MovingWorld/mrot
