### ISSUE TITLE
MaxBlock will be ignored in 1.7.10

### ISSUE THREAD

**Issue by PumaBlack** [darkevilmac/archimedes-ships-plus#49]
Hi,

i have a problem with the MaxBlocks Value. Default is 2.048 i know. But...   I run a 1.6.4 Tekkit-Server with the older Shipmod (without the crates), In this mod i have overwrited the maxblock value with the "dirty Joe" Software and set it to 30.720 Blocks. The config.cfg was ignored all the time.

Ingame the Shipsize become roundabout 15.000 to 18.000 Blocks and the 1GB RAM Server runs without lags. Client runs with 5GB for Java. Of course i had to wait 20 Seconds to mount the ship, but hey, 18.000 Blocks ;)

Now with the New Mod Archimedes Ships Plus in 1.7.10, i also changed the MaxBlock Value in the ArchimedesConfig.class to 30.720 Blocks, but i am not able to build ingame a bigger ship than 5.700 Blocks.
The GUI where you can assamble and mount the ship does not show the amount of blocks proper, if the ship is bigger than 5.700 Blocks.

What can ich do, or where i have to look to fix that issue?

For the Future, please enlarger the amout of MaxBlock much more. The Haribot Airship Mod has no problems even with 90.000 Blocks or more. But! It cant handle Items in a furnace or machines.

Your Mod is incredible amazing - but the 2048 limit is like a Lamborghini with an Hairdryer as Engine ;D

**Comment by darkevilmac** [comment]
I'm unable to recreate this. Please make sure you're using the MovingWorld configuration when it applies.

I'm fairly sure maxblocks has been transferred to MovingWorld but I could be wrong.
