### ISSUE TITLE
Suggestion: Replace custom movement keys with default player movement

### ISSUE THREAD

**Issue by lucom** [darkevilmac/archimedes-ships-plus#5]
Instead of using custom keys to move the ship it would be great to be able to use the default movement keys:
A/D: turning, W/S accelerate/decelerate
SPACE / SHIFT: Up / Down
E: Ship inventory
CTRL: Break
Right Click: Menu with options to align, dismount, destroy, etc...

**Comment by darkevilmac** [comment]
@lucom Please make sure to give your issues the proper tags.

**Comment by darkevilmac** [comment]
Would cause too many issues, left shift is occupied for dismounting.

**Comment by Niko-sk2x** [comment]
Which is the worst possible keybind I can think of because anyone used to creative will try to descend using shift. Which is usually done when you are high up, leading to death.

**Comment by darkevilmac** [comment]
You answered your own question about why its not shift, I'm not changing default binds.
