### ISSUE TITLE
Crash when Opening Ship Inventory [1.7.10]

### ISSUE THREAD

**Issue by Kumomo** [darkevilmac/archimedes-ships-plus#51]
If the ship collides with certain blocks when attempting to open the ship inventory (regardless if there is a chest or engine on the boat-airborne or otherwise), the client crashes. This does not seem to happen every time but is pretty frequent. I tried testing on flower and grass/tall grass blocks. When there is no collision, the ship inventory opens without issue and shows the disassemble/align buttons.
Crash Report: http://pastebin.com/uZ8fkdUa

The issue also exists when only Archimedes' Ships Plus and Moving World are installed without other mods, but does not result in a crash report. Rather than closing the client, it kicks me out of the single player world and back to the title screen after the error. It results in the error "A fatal error has occurred, this connection is terminated".

This occurs both in singleplayer and multiplayer. If the ship is partway through a solid block (tried on sand) it also seems to crash if I try to open the ship inventory.

Items tested that resulted in crashes/disconnects most of the time include sugar cane, grass, tall grass, dead bush, sand, spruce plank. When the ship is an entity, it doesn't seem to know when it runs into corners or singular blocks or non solid blocks like plants. The crash only occurs when opening the ship inventory though.

**Comment by darkevilmac** [comment]
It's an issue that I had thought I had fixed but apparently not, I'll look into it some mode.
