### ISSUE TITLE
closed last one by mistake sorry: fps drop 

### ISSUE THREAD

**Issue by reachmasters117** [darkevilmac/archimedes-ships-plus#52]
when we use this on eithe rour server or even on single player there is a MASSIVE drop in fps when mounting a ship, moving a ship or even standing near a ship these ships are no bigger than 500-1000 blocks and they worked fine on 1.7.10 we have moving world etc we just cant figure out whats cauing this massive fps drop i even loaded minecraft up with just the mod and moving world to see if it would be better and yet again my fps went from 60 to 10-15 when in a ship....

**Comment by darkevilmac** [comment]
Please make sure to follow guidelines and be more clear.

1.8 uses a different rendering system for ships, it's more accurate at the cost of being more resource intensive. This is more of a hardware issue on your end as I'm not noticing any major frame drops between 1.7 and 1.8.

If you could please list your specs that would be a big help, as well as give your fml-latest log.

Closing until more information is given.

**Comment by reachmasters117** [comment]
processor: Intel (R) Celeron(R) 
cpu N2830 2.16GHz
RAM: 4.00gb 

and running windows 10


on 1.7 with the same spec i would loose no frames but on 1.8 (with optifine installed) my frames crashed big time (tried without optifine same issue) my friend has same spec and he has the same issue is there a way to use the 1.7 rending engine like a seperate download because not having ships has takin a massive part of the RPG element we had out of the game
