### ISSUE TITLE
Crash Occured By Opening Ship's Helm

### ISSUE THREAD

**Issue by MCmariocraft** [darkevilmac/archimedes-ships-plus#53]
When I open my ship's helm to assemble, it freezes at status screen and soon the game crashes. I tried it about 4~5 times, but nothing was solved. Here's my crash report: http://pastebin.com/Q2NAiVPd

**Comment by darkevilmac** [comment]
See #51

**Comment by darkevilmac** [comment]
Same issue as #55

**Comment by darkevilmac** [comment]
dc28d19
