### ISSUE TITLE
Ships don't respect forbidden blocks [mc 1.7.10; ASP 1.8]

### ISSUE THREAD

**Issue by GrinningMoon** [darkevilmac/archimedes-ships-plus#54]
What's expected:
Ships to not assemble with blocks listed in the S:forbidden_blocks section in the Main.cfg (MovingWorld). For example, if minecraft:mob_spawner were listed, it wouldn't be picked up.

What happens:
Even if blocks are listed in the Main.cfg file for MovingWorld, they are still picked up. This includes the ArchimedesShipsPlus:buffer already listed in the config. However, other blocks such as dirt, sand, and clay don't assemble with the ship.

Possible solutions:
I believe there must be some kind of disconnect between Archimedes Ships Plus and MovingWorld. ASP must not be pulling the list in. This is evident considering it still 'forbids' vanilla minecraft blocks like the original did but because the ArchimedesShipsPlus:buffer has a different name than the original ArchimedesShips:buffer, my guess is it's still running off the old list.

**Comment by darkevilmac** [comment]
I know what's causing this I'll try and make a fix soon .
