### ISSUE TITLE
Furniture Flipping in Mr. Crayfish's Furniture Mod

### ISSUE THREAD

**Issue by JBelCOOL** [darkevilmac/archimedes-ships-plus#58]
When you put furniture from Mr. Crayfish's Furniture Mod on a ship, then assemble, mount, and disassemble, the direction of the blocks changes.

**Comment by darkevilmac** [comment]
Read the info on how to make an issue report before making an issue report. It's not that hard.

**Comment by darkevilmac** [comment]
See #59
