### ISSUE TITLE
Mod incompatibility with Mr. Crayfish's Furniture Mod

### ISSUE THREAD

**Issue by JBelCOOL** [darkevilmac/archimedes-ships-plus#59]
The orientation of the blocks is not modified when you turn your ship (they stay facing the compass direction they were placed in).
I appreciate that it will be difficult to fix, but I though I might make sure you know.
MC 1.7.10, Forge 10.13.4.1448, Latest versions of Archimedes ships plus and MovingWorld(on curse).

**Comment by darkevilmac** [comment]
1.7.10 does not have auto rotation discovery that was made possible in 1.8 from blockstates. Create a .mrot file for the furniture mod other than that there's not much I can do because custom exceptions for mods is not something I will be doing.
