### ISSUE TITLE
Making the steam engine required to move

### ISSUE THREAD

**Issue by Jhary** [darkevilmac/archimedes-ships-plus#6]
I would like to request a feature. The mod has this steam engine that if used on your ship makes it faster. Can you add a config option so adding and fueling a steam engine is mandantory for every ship to even move a single block? 

Would be awesome :)

P.S. : I don't know how to add the "features" tag

**Comment by darkevilmac** [comment]
I've gone ahead and added the labels for you, I mixed up the word label and tag sorry about that.

**Comment by Jhary** [comment]
If you still consider to add that feature, will it be in the 1.7 version? That would be nice

**Comment by darkevilmac** [comment]
Now implemented, sorry for the wait.

**Comment by darkevilmac** [comment]
https://github.com/darkevilmac/archimedes-ships-plus/commit/38aa6f6cfe323eeea1ff05dd6fc12fcb13c31923

**Comment by Jhary** [comment]
Oh thats just perfect :) Thank you for that!
