### ISSUE TITLE
Crash on Server while trying to align and disassemble

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [darkevilmac/archimedes-ships-plus#60]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 11/7/15 10:48 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: darkevilmac.archimedes.client.gui.GuiShip

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['awkwaRdcaRRot'/408422, l='MpServer', x=804.26, y=69.24, z=315.10], EntityOtherPlayerMP['gwillia8'/383813, l='MpServer', x=772.84, y=63.00, z=298.31]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (24,64,-25), Chunk: (at 8,4,7 in 1,-2; contains blocks 16,0,-32 to 31,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3951580 game time, 5545830 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 142 total; [EntityCartChest['entity.MinecartChest.name'/403458, l='MpServer', x=782.50, y=18.34, z=314.50], EntityItem['item.item.1MinicioEssence'/407810, l='MpServer', x=743.53, y=73.13, z=268.44], EntityItemFrame['Item Frame'/403459, l='MpServer', x=776.06, y=64.50, z=307.50], EntityItemFrame['Item Frame'/403456, l='MpServer', x=775.94, y=64.50, z=298.50], EntityWolf['Wolf'/403457, l='MpServer', x=777.69, y=64.00, z=289.94], EntityItem['item.item.bone'/407809, l='MpServer', x=744.56, y=71.13, z=269.78], EntitySquid['Squid'/408334, l='MpServer', x=825.53, y=59.00, z=328.53], EntitySquid['Squid'/408335, l='MpServer', x=832.90, y=59.13, z=314.83], EntityCreeper['Creeper'/408332, l='MpServer', x=772.50, y=34.00, z=357.50], EntityClientPlayerMP['awkwaRdcaRRot'/408422, l='MpServer', x=804.26, y=69.24, z=315.10], EntityConcussionCreeper['Concussion Creeper'/409097, l='MpServer', x=827.50, y=20.00, z=314.50], EntitySquid['Squid'/408342, l='MpServer', x=838.19, y=59.16, z=318.97], EntitySquid['Squid'/408343, l='MpServer', x=836.66, y=60.31, z=317.81], EntitySquid['Squid'/408340, l='MpServer', x=817.92, y=61.35, z=318.55], EntitySquid['Squid'/408341, l='MpServer', x=832.62, y=61.40, z=311.96], EntitySquid['Squid'/408338, l='MpServer', x=834.47, y=59.00, z=315.89], EntitySquid['Squid'/408339, l='MpServer', x=834.19, y=60.36, z=313.39], EntitySquid['Squid'/408336, l='MpServer', x=820.96, y=59.29, z=318.79], EntitySquid['Squid'/408337, l='MpServer', x=826.21, y=60.22, z=327.64], EntityBat['Bat'/408606, l='MpServer', x=838.27, y=30.14, z=274.09], EntitySkeleton['Skeleton'/408862, l='MpServer', x=846.50, y=29.00, z=251.50], EntitySkeleton['Skeleton'/408863, l='MpServer', x=847.50, y=28.00, z=250.06], EntityBat['Bat'/408093, l='MpServer', x=756.49, y=29.83, z=254.71], EntitySquid['Squid'/408344, l='MpServer', x=837.28, y=61.94, z=312.16], EntitySquid['Squid'/408345, l='MpServer', x=837.63, y=59.13, z=320.38], EntityBat['Bat'/408612, l='MpServer', x=840.57, y=32.20, z=280.25], EntityEnderman['Enderman'/408367, l='MpServer', x=844.50, y=41.00, z=280.34], EntityItem['item.item.feather'/407855, l='MpServer', x=785.13, y=69.13, z=269.25], EntitySpider['Spider'/407087, l='MpServer', x=869.50, y=67.00, z=386.50], EntityZombie['Zombie'/407082, l='MpServer', x=735.50, y=20.00, z=348.50], EntityBat['Bat'/408374, l='MpServer', x=867.19, y=39.00, z=309.64], EntityChicken['Chicken'/403767, l='MpServer', x=821.44, y=65.00, z=388.44], EntityBat['Bat'/408895, l='MpServer', x=844.75, y=28.00, z=300.62], EntityOtherPlayerMP['gwillia8'/383813, l='MpServer', x=772.84, y=63.00, z=298.31], EntityItem['item.item.bone'/408388, l='MpServer', x=763.88, y=73.13, z=263.69], EntityBat['Bat'/406593, l='MpServer', x=789.75, y=24.10, z=247.53], EntitySquid['Squid'/405065, l='MpServer', x=818.19, y=61.34, z=356.63], EntitySkeleton['Skeleton'/408151, l='MpServer', x=786.50, y=18.00, z=283.50], EntityBat['Bat'/407646, l='MpServer', x=791.25, y=19.10, z=253.50], EntityItem['item.item.rottenFlesh'/406879, l='MpServer', x=808.53, y=61.13, z=311.66], EntityCreeper['Creeper'/408415, l='MpServer', x=785.50, y=39.00, z=265.50], EntitySkeleton['Skeleton'/408921, l='MpServer', x=844.50, y=27.00, z=384.50], EntityItemFrame['Item Frame'/403302, l='MpServer', x=792.94, y=65.50, z=291.50], EntityShip['entity.ArchimedesShipsPlus.shipmod.name'/408423, l='MpServer', x=804.27, y=66.63, z=316.10], EntityItem['item.item.sulphur'/406885, l='MpServer', x=856.25, y=69.13, z=351.06], EntityXPOrb['Experience Orb'/406882, l='MpServer', x=815.31, y=60.25, z=315.44], EntityXPOrb['Experience Orb'/406883, l='MpServer', x=811.50, y=60.25, z=312.25], EntityCreeper['Creeper'/408416, l='MpServer', x=787.50, y=39.00, z=265.50], EntityXPOrb['Experience Orb'/406881, l='MpServer', x=812.13, y=60.25, z=313.34], EntityCartChest['entity.MinecartChest.name'/403304, l='MpServer', x=826.50, y=25.50, z=304.50], EntityCartChest['entity.MinecartChest.name'/401782, l='MpServer', x=854.50, y=21.34, z=307.50], EntitySkeleton['Skeleton'/408692, l='MpServer', x=800.50, y=56.00, z=382.50], EntityZombie['Zombie'/408691, l='MpServer', x=800.50, y=56.00, z=383.50], EntitySkeleton['Skeleton'/408435, l='MpServer', x=748.50, y=36.00, z=373.50], EntityItem['item.item.enderFragment'/405360, l='MpServer', x=749.88, y=63.13, z=364.41], EntityItem['item.item.sulphur'/405361, l='MpServer', x=749.56, y=63.13, z=363.75], EntityPig['Pig'/401788, l='MpServer', x=854.50, y=69.00, z=320.25], EntityCreeper['Creeper'/408186, l='MpServer', x=836.72, y=54.00, z=279.09], EntitySkeleton['Skeleton'/408187, l='MpServer', x=833.50, y=54.00, z=273.50], EntityCreeper['Creeper'/408184, l='MpServer', x=833.50, y=54.00, z=272.50], EntityPig['Pig'/401784, l='MpServer', x=855.03, y=69.00, z=382.84], EntityCreeper['Creeper'/408185, l='MpServer', x=830.50, y=54.00, z=272.50], EntityBat['Bat'/408199, l='MpServer', x=758.31, y=41.64, z=286.19], EntityCreeper['Creeper'/407437, l='MpServer', x=842.50, y=22.00, z=297.50], EntityItem['item.item.arrow'/407693, l='MpServer', x=745.88, y=72.13, z=263.19], EntityWitch['Witch'/407689, l='MpServer', x=780.50, y=18.00, z=324.50], EntitySeat['entity.ArchimedesShipsPlus.attachment.seat.name'/408469, l='MpServer', x=804.27, y=66.63, z=316.10], EntityChicken['Chicken'/10900, l='MpServer', x=785.22, y=69.00, z=268.78], EntitySkeleton['Skeleton'/407699, l='MpServer', x=752.31, y=27.00, z=254.75], EntityItemFrame['Item Frame'/10903, l='MpServer', x=788.50, y=65.50, z=278.06], EntityWolf['Wolf'/10905, l='MpServer', x=786.41, y=64.00, z=283.22], EntityCreeper['Creeper'/406173, l='MpServer', x=851.50, y=70.00, z=362.50], EntityCartChest['entity.MinecartChest.name'/405661, l='MpServer', x=683.50, y=34.50, z=425.13], EntitySkeleton['Skeleton'/408989, l='MpServer', x=795.50, y=17.00, z=282.50], EntityZombie['Zombie'/10912, l='MpServer', x=799.59, y=50.00, z=267.00], EntityOtherPlayerMP['gwillia8'/383813, l='MpServer', x=772.84, y=63.00, z=298.31], EntitySheep['Sheep'/405415, l='MpServer', x=734.38, y=64.00, z=390.09], EntitySheep['Sheep'/405413, l='MpServer', x=733.09, y=64.00, z=390.09], EntityPig['Pig'/403106, l='MpServer', x=802.50, y=77.00, z=299.50], EntityCreeper['Creeper'/409006, l='MpServer', x=826.50, y=34.00, z=259.50], EntityCreeper['Creeper'/409007, l='MpServer', x=829.50, y=34.00, z=256.50], EntityZombie['Zombie'/403114, l='MpServer', x=814.97, y=60.00, z=281.50], EntityPig['Pig'/403112, l='MpServer', x=835.06, y=70.00, z=357.97], EntityPig['Pig'/403113, l='MpServer', x=845.47, y=63.00, z=325.03], EntityHorse['Jack'/405417, l='MpServer', x=739.49, y=64.00, z=386.09], EntityCreeper['Creeper'/407474, l='MpServer', x=762.50, y=32.00, z=358.50], EntityCreeper['Creeper'/406470, l='MpServer', x=776.50, y=30.00, z=240.50], EntityBat['Bat'/408263, l='MpServer', x=839.27, y=54.28, z=280.33], EntityChicken['Chicken'/405198, l='MpServer', x=743.34, y=64.00, z=389.84], EntityChicken['Chicken'/405455, l='MpServer', x=735.78, y=64.00, z=383.78], EntityBat['Bat'/408269, l='MpServer', x=843.29, y=44.24, z=281.38], EntitySheep['Sheep'/405197, l='MpServer', x=733.47, y=64.00, z=392.31], EntityCartChest['entity.MinecartChest.name'/405453, l='MpServer', x=722.50, y=31.52, z=428.50], EntityBat['Bat'/408267, l='MpServer', x=844.23, y=39.26, z=279.17], EntityBat['Bat'/408264, l='MpServer', x=837.40, y=54.78, z=276.28], EntityItemFrame['Item Frame'/51407, l='MpServer', x=788.50, y=66.50, z=278.06], EntityCow['Cow'/405206, l='MpServer', x=751.25, y=64.00, z=373.34], EntityPig['Pig'/405204, l='MpServer', x=748.75, y=64.00, z=378.06], EntityPig['Pig'/405205, l='MpServer', x=751.31, y=64.00, z=372.09], EntityCow['Cow'/405202, l='MpServer', x=745.09, y=64.00, z=372.09], EntityChicken['Chicken'/405203, l='MpServer', x=749.91, y=64.00, z=371.78], EntityChicken['Chicken'/405200, l='MpServer', x=738.06, y=64.00, z=391.75], EntityZombieVillager['Villager Zombie'/316883, l='MpServer', x=779.00, y=52.00, z=305.50], EntityPig['Pig'/404959, l='MpServer', x=758.13, y=64.00, z=395.19], EntityChicken['Chicken'/405208, l='MpServer', x=749.44, y=64.00, z=385.44], EntityCow['Cow'/404966, l='MpServer', x=760.44, y=64.00, z=375.31], EntitySheep['Sheep'/404967, l='MpServer', x=754.38, y=64.00, z=378.28], EntityChicken['Chicken'/404964, l='MpServer', x=756.31, y=64.00, z=371.78], EntityChicken['Chicken'/404965, l='MpServer', x=752.38, y=64.00, z=379.22], EntityCow['Burger'/404962, l='MpServer', x=761.28, y=64.00, z=382.75], EntityZombieDog['entity.GraveStone.GSZombieDog.name'/408802, l='MpServer', x=897.31, y=35.00, z=300.47], EntityCow['Cow'/404963, l='MpServer', x=754.78, y=64.00, z=372.09], EntitySheep['Sheep'/404960, l='MpServer', x=746.09, y=64.00, z=387.84], EntityZombieDog['entity.GraveStone.GSZombieDog.name'/408801, l='MpServer', x=891.50, y=33.00, z=302.50], EntityChicken['Chicken'/404974, l='MpServer', x=759.28, y=64.00, z=374.56], EntityChicken['Chicken'/404975, l='MpServer', x=753.94, y=64.00, z=371.78], EntityZombie['Zombie'/400620, l='MpServer', x=871.30, y=42.00, z=263.69], EntityPig['Pig'/404972, l='MpServer', x=752.97, y=64.00, z=372.34], EntitySheep['Sheep'/400621, l='MpServer', x=874.09, y=63.00, z=259.09], EntityChicken['Chicken'/404973, l='MpServer', x=758.81, y=64.00, z=372.88], EntitySheep['Sheep'/404970, l='MpServer', x=759.69, y=64.00, z=373.56], EntityPig['Pig'/400619, l='MpServer', x=879.72, y=73.00, z=359.09], EntitySheep['Sheep'/404971, l='MpServer', x=757.97, y=64.00, z=372.09], EntitySheep['Sheep'/404968, l='MpServer', x=760.38, y=64.00, z=372.09], EntityCow['Cow'/404969, l='MpServer', x=759.09, y=64.00, z=372.09], EntityCartBasic['entity.MinecartRideable.name'/403446, l='MpServer', x=761.78, y=11.50, z=245.50], EntityHorse['Pip'/404983, l='MpServer', x=754.84, y=64.00, z=383.75], EntityCartChest['entity.MinecartChest.name'/403447, l='MpServer', x=760.25, y=11.50, z=245.50], EntityCartChest['entity.MinecartChest.name'/403444, l='MpServer', x=747.59, y=22.34, z=279.56], EntityLocomotiveSteamSolid['Steam Locomotive'/403445, l='MpServer', x=763.50, y=11.50, z=245.50], EntityCartChest['entity.MinecartChest.name'/405493, l='MpServer', x=713.50, y=28.50, z=352.50], EntityZombie['Zombie'/408304, l='MpServer', x=785.50, y=39.00, z=266.50], EntityChicken['Chicken'/404976, l='MpServer', x=752.38, y=64.00, z=377.41], EntityZombie['Zombie'/408305, l='MpServer', x=784.50, y=39.00, z=264.50], EntityZombieVillager['Villager Zombie'/406012, l='MpServer', x=872.50, y=70.00, z=355.50], EntityZombie['Zombie'/403452, l='MpServer', x=756.75, y=18.00, z=252.91], EntitySpeedBoat['Speed Boat'/403453, l='MpServer', x=763.00, y=63.19, z=297.19], EntityCartBasic['entity.MinecartRideable.name'/403450, l='MpServer', x=755.53, y=11.50, z=245.50], EntityZombie['Zombie'/403451, l='MpServer', x=756.50, y=18.00, z=248.00], EntityArmourStand['Armour Stand'/403192, l='MpServer', x=779.50, y=64.00, z=281.50], EntityCartChest['entity.MinecartChest.name'/403448, l='MpServer', x=758.66, y=11.50, z=245.50], EntityCartChest['entity.MinecartChest.name'/403449, l='MpServer', x=757.13, y=11.50, z=245.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 885730248 bytes (844 MB) / 2249195520 bytes (2145 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4608m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_U_C1 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJA	ExpandedIndustry{10.17.0a} [Expanded Industry] (1.7.10-ExpandedIndustry-10.17.0a.jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJA	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8.jar) 
	UCHIJA	ArchimedesShipsPlus{1.7.10-1.8} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHIJA	D3Core{1.1.0.31} [D3Core] (D3Core-1.7.10-1.1.0.31.jar) 
	UCHIJA	AutoCrafter2000{1.1.0.33} [AutoCrafter2000] (AutoCrafter2000-1.7.10-1.1.0.33.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCHIJA	bluepower{0.2.962} [Blue Power] (BluePower-1.7.10-0.2.962-universal.jar) 
	UCHIJA	Botania{r1.7-228} [Botania] (Botania r1.7-228.jar) 
	UCHIJA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJA	etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJA	GraveStone{2.13.0} [GraveStone] (GraveStone-2.13.0.jar) 
	UCHIJA	HelperToolsID{1.1.5M} [HelperTools] (HelperTools-1.7.10-1.1.5M.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJA	ironchestminecarts{1.0.3} [Iron Chest Minecarts] (IronChestMinecarts-1.0.3.jar) 
	UCHIJA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJA	Morpheus{1.7.10-1.6.10} [Morpheus] (Morpheus-1.7.10-1.6.10.jar) 
	UCHIJA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJA	openmodularturrets{2.1.5-184} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.5-184.jar) 
	UCHIJA	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCHIJA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJA	StevesAddons{0.10.16} [Steve's Addons] (StevesAddons-1.7.10-0.10.16.jar) 
	UCHIJA	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	wawla{1.3.2} [What Are We Looking At] (Wawla-1.3.2-1.7.10.jar) 
	UCHIJA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.87' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: forge-10.13.4.1517
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip, JSTR_Universal_1.7.x.zip, Custom.zip, BDcraft Sounds Pack.zip, BDcraft Musics Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Wolfofthenyght** [comment]
Can I ask why this was closed? I'm having the same issue on my server, and I'd like to know if there is or was a fix for it? Thank you!

**Comment by darkevilmac** [comment]
Edited both of your messages, not trying to be rude just please try and follow the guidelines. I recommend opening a new issue and following the instructions @Wolfofthenyght

**Comment by Wolfofthenyght** [comment]
Well, since my response is now gone, I'm not even sure of what I wrote that wasn't in line with your guidelines. It's fine, I'll just wait for an update and see if it's fixed.

**Comment by darkevilmac** [comment]
Pretty much the entire thing, title was fine, message needed a bit more information and proper formatting, and the crash log was posted in the post and not externally like suggested.
