### ISSUE TITLE
Mod installation problem

### ISSUE THREAD

**Issue by Oravaliito** [darkevilmac/archimedes-ships-plus#61]
Forge Mod Loader has found a problem with your minecraft installation
You have mod sources that are dublicate within your system
Mod Id : File name
darkevilmac.movingworld.common.asm.coremod : minecraft.jar

Why this mod even have to had a second mod like moving world, cannot it be just made for ordinary archimedes ships mod I used to have in 1.7.10, working with even three times more mods. I have few with 1.8...

**Comment by darkevilmac** [comment]
If you'd look into it a little bit more you would understand why MovingWorld exists. It's infinitely more easy to develop with.

On another note, this has been asked tons of times. Update to the latest forge, make sure that if you have sponge/forgeessentials installed that it's on the most up to date version as well. It's not an issue on my part and has had countless issues created about it that I've closed.

See: https://github.com/darkevilmac/MovingWorld/issues/11
