### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by tylerspencer237** [darkevilmac/archimedes-ships-plus#65]
I was wondering if updating from Archimedes' Ships to Archimedes' Ships Plus would transition existing blocks from a world to ASP format. I am running a server but the memory leaks kill it so I'm intending on replacing AS.

**Comment by darkevilmac** [comment]
It should transition fine, essentially what you need to do is the following,

Disassemble all ships in your worlds, backup your world and configs, remove the original archimedes ships, install MovingWorld, install AS+, start your server and wait for a minute it could take longer than usual. And then you're good to go.

**Comment by darkevilmac** [comment]
Just a note, there's some issues with some more recent forge versions at the moment due to some changes in method names that needs to be adjusted by the mixin developers but that won't take too long.
