### ISSUE TITLE
(1.8.9) Cannot Rename or Assemble ship while in a server

### ISSUE THREAD

**Issue by DarcClan** [darkevilmac/archimedes-ships-plus#67]
If i try to assemble or rename a ship that has been pieced together i get booted from the server saying "A fatal error has occured, this connection is terminated". Server stays open though and doesn't crash

**Comment by mrgreaper** [comment]
same error, just looked through the logs and cant find anything

made a simple ship with just birch planks birch stairs, a crafting table(vanilla) cyan balloons and the helm, made it in the air so not touching anything, same error

**Comment by darkevilmac** [comment]
Please actually follow contributing.md, it's even in your face before an issue is made.

http://i.imgur.com/jFVFfEQ.png

I'll give you a hint as to what you didn't include, the first thing listed. Please edit the original post and I'll reopen.
