### ISSUE TITLE
(1.7.10) Config does not change allowable balloons, material or block densities

### ISSUE THREAD

**Issue by Alaberti** [darkevilmac/archimedes-ships-plus#69]
I tried adding my own changes to the config as far as changing the types of balloons and densities nothing I've changed seems to be taking effect.

Config: http://pastebin.com/DkiiMtyv

**Comment by darkevilmac** [comment]
Full log or it didn't happen.

**Comment by Alaberti** [comment]
https://gist.github.com/Alaberti/057e4b78e760307baee9

**Comment by Alaberti** [comment]
Version 1.8.1 - Confirmed, block/material densities work now. Adding blocks to the balloons list still has no effect, however.

**Comment by darkevilmac** [comment]
I'll take a look at the balloon stuff. Glad to see the changes to material density worked though.
