### ISSUE TITLE
Crash when assembling vehicle

### ISSUE THREAD

**Issue by mrgreaper** [darkevilmac/archimedes-ships-plus#73]
Do NOT post your error in the issue directly, please use http://hastebin.com/ or http://pastebin.com/
http://pastebin.com/1ULN5ENY
Do NOT post the entire description of your error in the title, the title is just a very short explanation.
Tick
DO post information about the crash you were able to discover in the actual issue text.
strange request, might make it hard for others to find the same crash via oogle but ok its in the pastebin
DO see if the issue occurs with just AS+ and MovingWorld installed, so I know if it's an incompatibility Unable to test this at this time, i should get some free time saturday and if needed can test that out, however if it did not crash when you tested on a test server then that should say its a mod incompatability, let me know that and ill test one by one with my other mods on saturday and tell you the incompatable ones (should you wish this knowledge)
For any report at all you must list the AS+ version, the MovingWorld version, the Forge version, and the Minecraft version. If this is not done the issue will be closed.
minecraft 1.8.9
moving world indev-full (yeah not helpful but thats what it reports as)
AS+ Indev (again no version number sorry but thats how it reports, may be first and only 1.8.9 version)

extra notes, work on mods by modders is appreciated, as an ex modder i know the work that goes into them, reporting an issue should help alert you to possible issues, they are not ment as a HELP ITS BROKE FIX IT FIX IT but just a hay, heads up you got an issue, server admins have limited time the same as modders, we field reports from players and i know how annoying that can be, but it is equally annoying to recieve a slightly hostile reply and have the issue closed (sorry but i always speak my mind, its who i am, im also the sort of person thats happy to spend a few hours saturday testing for incompatable mods if needed)

**Comment by darkevilmac** [comment]
Said to EDIT the issue previously posted, as well as include a crash log, not a description on pastebin.
