### ISSUE TITLE
[1.7.10] Cannot mount without reassembling

### ISSUE THREAD

**Issue by wscalf** [darkevilmac/archimedes-ships-plus#78]
We're using Archimedes+ in a modified version of the FTB: Infinity Evolved pack, and we're having a pretty nasty issue: every time we try to mount a ship, no matter how simple it is, the 'Mount' option is grayed out and we have to assemble. ..Which means pulling in unintended changes.

Back when we used Archimides Ships (not plus), that used to work - the 'Mount' option would only be grayed out if we had removed blocks that used to be part of the ship, but it seems to be every time now.

Thoughts/Suggestions? I looked around to see if there were maybe a setting or something, but nothing sticks out.

**Comment by darkevilmac** [comment]
Lost this functionality in the transition between MovingWorld's transition. I'll look into reimplementing it somehow. Please move this issue to the MovingWorld repo.
