### ISSUE TITLE
Suggestions for Engines & More

### ISSUE THREAD

**Issue by KirinGuardian** [darkevilmac/archimedes-ships-plus#9]
Greetings Darkevilmac!

First off, as a game design student and novice coder, I wanted to offer my gratitude that you've taken the helm (sorry, pun) of this ship mod. I know how few people realize the amount of work that goes into this, let alone appreciate that you're doing so (in most cases) for free.

Now for the suggestions. Again, by all means take as much time as you need should you consider any of them viable:
1) Engine Types:
- Possibly only enabled if other mods are (configurable otherwise), such as a liquid fueled engine for Oil, Fuel, etc., and an Electric or Redstone Flux fueled engine. Different engines could offer different acceleration in proportion to the mass of the ship. (Depending on your skill with coding and models in Minecraft, propellers or jets would be a pleasing visual aesthetic, but by no means high priority.)

2) Either:
    a) Chests that are part of the ship increase space/contents are shown in the "ship inventory", or 
    b) A Cargo Hold block to increase ship inventory, accessible via the ship GUI.

3) Loaders/Unloaders:
- Thanks to your Anchor Block, precise parking of a ship is now reliably possible. This opens up the option for players to create specialize docks for refueling & loading/unloading of cargo. This is currently doable, but only so long as the players don't assemble the ship while attached to these, so we can add them to the black list of ship blocks for now, but doing so limits possible contraptions within the ship. So, if your mod provided a variant that combined the shore buffer with item/fluid/energy pipes, problem solved.

4) Landing Gear or "Hull" blocks:
- "Simply," blocks that will connect to the ship on assembly from one side, but no others. I realize the coding for this is likely complex, which is why I use Ropes+ grappling hooks to get in and out of airships without parking nearing anything, but the idea is that the blocks will act as a border in ship assembly, so adjacent blocks won't be added to the ship, but the block itself will, forming outside of the ship, or at minimum a landing gear that won't try to connect the ship to the ground/trees/houses/etc..

5) Entry/Exit options:
- Speaking of Ropes+, Luppi's Ladders are another great way to get in and out of a ship, with retractable ladders. Perhaps along the lines of the engines, multiple tiers of entry/exit options could be available, from gang-plank, to drop stairs/ladders, to tractor beams or teleport blocks, possibly stand-on + LSHIFT sends you to the ground directly beneath it, with a linked hand-held item to get back. 

Some fun things to note that you may not have been aware of:
- Open Modular Turrets works well with Archimedes ships, just obviously not while the ship is in motion. Might be worth looking into for the Cannon feature request.
- EnderIO Conduits and their Conduit Facades make very good, compact, hidden wiring for Archimedes Ships, able to be part of the ship body.

**Comment by darkevilmac** [comment]
Oh boy. As you can most likely see by looking at some of the current notices a lot of my time right now is dedicated to moving a ton of code around. To make it less of a nightmare to do even the slightest of bugfixes. The reason for the slow development the past little while is due to real life getting in the way a bit. If you're interested in possibly talking to me a little more about these ideas I recommend going on my twitch stream when I'm live or going to the #WAMM channel in espernet and using a personal message as I'm there quite often.

**Comment by KirinGuardian** [comment]
I know the feeling all too well. As mentioned, I'm currently in college for game design myself, and while my art/modeling skills are passable, it seems my passion is game engineering and mechanics. I love setting up how things work. The downside being that college leaves little time for game development, particularly if one plays them to unwind after school work.

That said, I'd love to offer what help I can. I know a little javascript, Unityscript (Unity's take on javascript), and am currently taking a crash course in C#. If nothing else, I can go into better detail on how certain functions might work. I'm very interested to understand how this mod in particular does, as the creation of these ships is something I would love to add into my own creations.
