### ISSUE TITLE
Mounting a ship creates waterhole and thus makes the ship unable to move

### ISSUE THREAD

**Issue by GameBurrow** [darkevilmac/archimedes-ships-plus#91]
When you mount a ship on water, it creates waterhole as seen on the images:
http://i.imgur.com/JFn6r77.png
http://i.imgur.com/SguM1Vx.png
http://i.imgur.com/L0zgOaW.png
http://i.imgur.com/KgRyDxX.png

and thus you cannot move the ship out of the area. Would it be possible to get this fixed on 1.7.10

Technical details:
Issue found on the [Transportcraft](http://forum.thesociety.eu/index.php?threads/server-transportcraft.1798/) modpack
MC version: 1.7.1.0
Forge: 10.13.4.1614
Archimedes ships+ version: 1.8.1
[List of all other mods in the pack](https://docs.google.com/spreadsheets/d/1Co3FeGW-lgPir14zfpnnp-z7SvkZZn5euK2A2DU3n68/edit#gid=0)

**Comment by darkevilmac** [comment]
This has been the case for quite some time, build your ship ABOVE the water level and it figures out the rest. Building in the water displaces the water before you even built the ship, it doesn't know what was there before, that would require either some hacky fix or remembering every block a placer displaces...

Oh, and 1.7.10 development is pretty much done with, I'm focusing on 1.10 porting at the moment.

**Comment by GameBurrow** [comment]
Actually the issue on the pictures happened after dismounting the ship.

**Comment by darkevilmac** [comment]
> Actually the issue on the pictures happened after dismounting the ship.

Could you record a short video of the issue occuring when you build the ship above water, go for a drive then assemble and disassemble again? I'm not able to reproduce the issue.
