### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 5igm** [darkevilmac/archimedes-ships-plus#97]
Could you offer more blocks for max size of boats? Like 
Ship's Helm(100 blocks)
Ship's Helm(300 blocks)
Ship's Helm(500 blocks)
......

Could you develop some new blocks used to fight with other boats?
Like cannon used to attack others boats.

Could you develop a new consumption system for Steam Engine?
For example, coat, woods, etc. will be changed to energy, and different boats will consume different energy based on their size and speed.

Thank you very much. I like this mod so much!
^_^

**Comment by darkevilmac** [comment]
Potentially in the future.
