### ISSUE TITLE
Failed disassembly of ship may turn off gamerule "doTileDrops" permanently.

### ISSUE THREAD

**Issue by codewarrior0** [darkevilmac/archimedes-ships-plus#98]
This affects the 1.7.10 release, and judging by the MovingWorld sources for 1.10, also affects that version. It looks like the fix is to wrap a `try { ... } finally { /* revert "doTileDrops" gamerule */ }` around the relevant ship disassembly code.

Steps to reproduce:

Assemble a ship that has an active Portable Hole from Thaumcraft used on it. Mount the ship. Then, disassemble the ship.

**Comment by Hoborific** [comment]
Also have this problem.

**Comment by darkevilmac** [comment]
Not sure how I forgot about this, I know of the bug and I've had it before. Will fix in next build.

**Comment by codewarrior0** [comment]
Thanks! It was really frustrating to track this one down, since there would usually be some time between disassembling the buggy ship and finding out that blocks have mysteriously stopped dropping items when broken.
